/**
 * Monster Creator model — Monster Gate WS-A (see _specs/MONSTER-GATE-SPEC.md).
 *
 * The creator is a REFERENCE SCAFFOLD, not a CR calculator or auto-balancer: every value
 * it produces is a starting point the DM reviews and may override.
 *
 * Core rule (Christopher): ability scores are NOT generated by the archetype. Base scores
 * come from the CHASSIS — an existing stat block at the fight's projected CR, or the
 * encounter document that already has them. The archetype REDISTRIBUTES that same score
 * pool into a different shape (swap archetype -> same six numbers, new arrangement).
 *
 * GUARDRAIL (source model §11): no exact archetype AC-modifier table exists and none may
 * be invented — baseline AC references come from the party-level band only.
 */

import type { MonsterArchetype, MonsterClassification, MainMonsterTemplate } from "../runtime/mainMonsterRuntime";

// ─── Ability entry parsing ────────────────────────────────────────────────────
// Template abilities are display entries: { label: "STR", value: "16 (+3)" }.

export const ABILITY_ORDER = ["STR", "DEX", "CON", "INT", "WIS", "CHA"] as const;
export type AbilityLabel = (typeof ABILITY_ORDER)[number];

export function abilityModifier(score: number): number {
  return Math.floor((score - 10) / 2);
}

export function formatAbilityEntry(label: string, score: number): { label: string; value: string } {
  const mod = abilityModifier(score);
  return { label, value: `${score} (${mod >= 0 ? "+" : ""}${mod})` };
}

/** Parses "16 (+3)" / "16" / "+3"-less values back to a score. Returns 10 on garbage. */
export function parseAbilityScore(value: string): number {
  const match = value.trim().match(/^(\d+)/);
  const score = match ? Number.parseInt(match[1], 10) : NaN;
  return Number.isFinite(score) ? score : 10;
}

/** Reads a template's six scores in canonical order (missing entries default 10). */
export function scoresFromTemplate(abilities: { label: string; value: string }[]): Record<AbilityLabel, number> {
  const out = {} as Record<AbilityLabel, number>;
  for (const label of ABILITY_ORDER) {
    const entry = abilities.find(a => a.label.toUpperCase().startsWith(label));
    out[label] = entry ? parseAbilityScore(entry.value) : 10;
  }
  return out;
}

// ─── Archetypes — the six FDMC styles ─────────────────────────────────────────

export type ArchetypeInfo = {
  id: MonsterArchetype;
  label: string;
  primary: AbilityLabel;
  /**
   * Stat priority order for redistribution: the chassis's six scores, sorted high→low,
   * are dealt to these slots in order. CON always rides second — the source model's
   * "secondary keeps Constitution relevant" rule — except for the Guardian, where CON
   * IS the primary. Orders are a tunable design choice, recorded here as data.
   */
  priority: AbilityLabel[];
  blurb: string;
};

export const ARCHETYPES: ArchetypeInfo[] = [
  { id: "bruiser", label: "Bruiser / Brute", primary: "STR", priority: ["STR", "CON", "DEX", "WIS", "CHA", "INT"], blurb: "Heavy melee, shove, grab, knockdown. Survives by body mass." },
  { id: "skirmisher", label: "Skirmisher / Hunter", primary: "DEX", priority: ["DEX", "CON", "WIS", "STR", "CHA", "INT"], blurb: "Mobile attacks, flank, hit-and-move. Avoidance over armor." },
  { id: "guardian", label: "Guardian / Endurance", primary: "CON", priority: ["CON", "STR", "DEX", "WIS", "CHA", "INT"], blurb: "Holds space, intercepts, punishes movement. The wall." },
  { id: "tactician", label: "Tactician / Caster", primary: "INT", priority: ["INT", "CON", "DEX", "WIS", "CHA", "STR"], blurb: "Saves, zones, control, limited high-impact spells." },
  { id: "mystic", label: "Mystic / Predator", primary: "WIS", priority: ["WIS", "CON", "DEX", "CHA", "STR", "INT"], blurb: "Ambush, tracking, fear, nature/divine effects." },
  { id: "commander", label: "Commander / Presence", primary: "CHA", priority: ["CHA", "CON", "WIS", "DEX", "STR", "INT"], blurb: "Commands, auras, ally movement, tactical support." },
];

export function archetypeInfo(id: MonsterArchetype): ArchetypeInfo {
  return ARCHETYPES.find(a => a.id === id) ?? ARCHETYPES[0];
}

/**
 * Redistribute a score pool by archetype: the SAME six numbers, dealt high→low into the
 * archetype's priority order. The pool is preserved exactly — swapping archetype changes
 * the creature's shape, never its total budget.
 */
export function redistributeScores(scores: Record<AbilityLabel, number>, archetype: MonsterArchetype): Record<AbilityLabel, number> {
  const pool = ABILITY_ORDER.map(l => scores[l]).sort((a, b) => b - a);
  const info = archetypeInfo(archetype);
  const out = {} as Record<AbilityLabel, number>;
  info.priority.forEach((label, i) => { out[label] = pool[i]; });
  return out;
}

/** Redistribute a template's formatted ability entries by archetype (Monster Gate A2). */
export function redistributeAbilityEntries(
  abilities: { label: string; value: string }[],
  archetype: MonsterArchetype,
): { label: string; value: string }[] {
  const reshaped = redistributeScores(scoresFromTemplate(abilities), archetype);
  return ABILITY_ORDER.map(label => formatAbilityEntry(label, reshaped[label]));
}

// ─── Classification options (creature axis — `normal` IS selectable) ──────────

export const CLASSIFICATION_OPTIONS: { value: MonsterClassification; label: string; blurb: string }[] = [
  { value: "normal", label: "Normal", blurb: "Rank-and-file. Fight target 2–2.5 rounds." },
  { value: "strong", label: "Strong", blurb: "Tougher threat. 2.25–3.5 rounds." },
  { value: "elite", label: "Elite", blurb: "Mini-boss / dangerous solo. 3.25–4.5 rounds." },
  { value: "mid-boss", label: "Mid-Boss", blurb: "Act midpoint set piece. 4–5.5 rounds." },
  { value: "act-boss", label: "Act Boss", blurb: "End of an act. 5–6.5 rounds." },
  { value: "final-boss", label: "Major Story Boss", blurb: "The final three bosses of the story. 6–8 rounds." },
];

// ─── Size categories ──────────────────────────────────────────────────────────

export const SIZE_OPTIONS = ["Tiny", "Small", "Medium", "Large", "Huge", "Gargantuan"] as const;

// ─── Party-level band AC / HP references (source model §7–§8) ────────────────
// Reference ONLY — shown next to the Defenses inputs with Apply buttons; the band
// never silently overwrites a value the DM typed.

export type CreatorBandId = "low" | "mid" | "high" | "extreme" | "final";
export type CreatorPressureId = "standard" | "strong" | "elite" | "bossGate";

export type CreatorBandRef = {
  id: CreatorBandId;
  label: string;
  baselineAc: number;
  attackBonus: number;
  starterDamage: string;
  hp: Record<CreatorPressureId, { low: number; high: number | null; suggested: number }>;
};

export const CREATOR_BANDS: CreatorBandRef[] = [
  {
    id: "low", label: "Low · party levels 1–4", baselineAc: 13, attackBonus: 4, starterDamage: "1d6 + 2",
    hp: { standard: { low: 11, high: 35, suggested: 22 }, strong: { low: 35, high: 55, suggested: 44 }, elite: { low: 55, high: 75, suggested: 65 }, bossGate: { low: 75, high: null, suggested: 90 } },
  },
  {
    id: "mid", label: "Mid · party levels 5–8", baselineAc: 15, attackBonus: 6, starterDamage: "2d6 + 3",
    hp: { standard: { low: 45, high: 90, suggested: 65 }, strong: { low: 90, high: 135, suggested: 110 }, elite: { low: 135, high: 190, suggested: 160 }, bossGate: { low: 190, high: null, suggested: 220 } },
  },
  {
    id: "high", label: "High · party levels 9–12", baselineAc: 17, attackBonus: 8, starterDamage: "3d8 + 4",
    hp: { standard: { low: 90, high: 160, suggested: 125 }, strong: { low: 160, high: 235, suggested: 195 }, elite: { low: 235, high: 320, suggested: 275 }, bossGate: { low: 320, high: null, suggested: 360 } },
  },
  {
    id: "extreme", label: "Extreme · party levels 13–16", baselineAc: 19, attackBonus: 10, starterDamage: "4d10 + 5",
    hp: { standard: { low: 160, high: 260, suggested: 215 }, strong: { low: 260, high: 380, suggested: 315 }, elite: { low: 380, high: 520, suggested: 450 }, bossGate: { low: 520, high: null, suggested: 600 } },
  },
  {
    id: "final", label: "Final · party levels 17–20", baselineAc: 21, attackBonus: 12, starterDamage: "6d10 + 6",
    hp: { standard: { low: 260, high: 420, suggested: 340 }, strong: { low: 420, high: 650, suggested: 520 }, elite: { low: 650, high: 900, suggested: 760 }, bossGate: { low: 900, high: null, suggested: 1000 } },
  },
];

export const PRESSURE_OPTIONS: { value: CreatorPressureId; label: string }[] = [
  { value: "standard", label: "Standard" },
  { value: "strong", label: "Strong" },
  { value: "elite", label: "Elite" },
  { value: "bossGate", label: "Boss / Gate" },
];

// ─── Chassis loading (Monster Gate A2) ────────────────────────────────────────

/** What a chassis hands the draft: scores + defenses, never actions/identity. */
export type ChassisPayload = {
  abilities: { label: string; value: string }[];
  ac: number | string;
  maxHp: number;
  speed: string;
};

export function chassisFromTemplate(t: MainMonsterTemplate): ChassisPayload {
  const scores = scoresFromTemplate(t.abilities);
  return {
    abilities: ABILITY_ORDER.map(label => formatAbilityEntry(label, scores[label])),
    ac: t.stats.ac,
    maxHp: t.stats.maxHp,
    speed: t.stats.speed,
  };
}
