/**
 * CERTIFIED LAST-KNOWN-GOOD ENGINE — generated by `npm run engine:certify`.
 *
 * ⚠ AN ARTIFACT, NOT SOURCE. Overwritten wholesale on the next certification. Editing it by hand
 * creates the second editable authority the portability spec forbids, and the hash in
 * `manifest.json` would stop describing what is here.
 *
 * engine 1.0.0 · dcfc23d3c99d · built 2026-08-28T17:15:37.189Z
 */
import * as capabilities from "./engine/encounter-engine/capabilities.js";

export const CAPABILITIES = capabilities;
export const ARTIFACT = {
  "engineVersion": "1.0.0",
  "hash": "dcfc23d3c99d",
  "builtAt": "2026-08-28T17:15:37.189Z",
  "appVersion": "0.8.6.0",
  "capabilities": [
    "estimateCreature",
    "resolvePartyProfile",
    "checkEncounter",
    "aggregateAudit",
    "auditCoverage"
  ]
};
