/**
 * REST RECOVERY REGISTRY — classes, subclasses and species; short rest AND long.
 *
 * ⚠ GENERATED from `Broken_Chain_Act_Creature_and_Encounter_Pricer_v4_Recovery_Corrected.xlsx`
 * (sheets "Class Recovery" and "Race Species Recovery") by `scripts/gen-recovery-registry.mjs`.
 * Do not hand-edit.
 *
 * ⚠ MOD CONTENT, NOT ENGINE. A rest is a 5e concept; the shape — a pool that refreshes on a named
 * cadence — is engine and lives in `core/types/tabs.ts`.
 *
 * ⚠ AND IT IS STRICTLY EDITION-KEYED. The workbook's own header: *"Strict edition lookup.
 * Long-Rest-only limited traits are retained when needed to prevent a false Short-Rest refresh."*
 * The 5.1 Dragonborn's Breath Weapon comes back on a short OR long rest and the 5.2.1 one does not;
 * flattening the two hands one edition a free recharge every hour.
 *
 * ⚠ THIS SUPERSEDES NOTHING YET. `shortRestRules.generated.ts` still carries the 135 subclass rows
 * that record "checked, grants nothing", which this sheet omits rather than contradicts — a row
 * saying "none" is an answer, and the two files answer different questions until they are
 * reconciled deliberately.
 *
 * 57 class rows (4 subclass-scoped) · 21 species rows (14 with a real pool)
 */

export type RecoveryMode = string;

export type ClassRecoveryRule = {
  ruleset: "5.2.1" | "5.1";
  scope: string;
  className: string;
  /** "" on a class-scoped rule. */
  subclassName: string;
  resource: string;
  minLevel: number;
  hitDie: string;
  capacityBasis: string;
  shortRestMode: RecoveryMode;
  shortRestAmount: string;
  longRestMode: RecoveryMode;
  longRestAmount: string;
  oncePerLongRest: boolean;
  engineKind: string;
  notes: string;
};

export type SpeciesRecoveryRule = {
  ruleset: "5.2.1" | "5.1";
  terminology: string;
  species: string;
  resource: string;
  minLevel: number;
  capacityBasis: string;
  shortRestMode: RecoveryMode;
  shortRestAmount: string;
  longRestMode: RecoveryMode;
  longRestAmount: string;
  engineKind: string;
  notes: string;
};

export const CLASS_RECOVERY: readonly ClassRecoveryRule[] = [
  { ruleset: "5.1", scope: "Core rest", className: "Barbarian", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d12", capacityBasis: "1 die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Dice; heal die + CON (minimum 0)", longRestMode: "REGAIN_HALF_HIT_DICE", longRestAmount: "Recover spent Hit Dice up to half total character Hit Dice, minimum 1", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.1", scope: "Core rest", className: "Bard", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d8", capacityBasis: "1 die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Dice; heal die + CON (minimum 0)", longRestMode: "REGAIN_HALF_HIT_DICE", longRestAmount: "Recover spent Hit Dice up to half total character Hit Dice, minimum 1", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.1", scope: "Core rest", className: "Cleric", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d8", capacityBasis: "1 die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Dice; heal die + CON (minimum 0)", longRestMode: "REGAIN_HALF_HIT_DICE", longRestAmount: "Recover spent Hit Dice up to half total character Hit Dice, minimum 1", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.1", scope: "Core rest", className: "Druid", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d8", capacityBasis: "1 die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Dice; heal die + CON (minimum 0)", longRestMode: "REGAIN_HALF_HIT_DICE", longRestAmount: "Recover spent Hit Dice up to half total character Hit Dice, minimum 1", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.1", scope: "Core rest", className: "Fighter", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d10", capacityBasis: "1 die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Dice; heal die + CON (minimum 0)", longRestMode: "REGAIN_HALF_HIT_DICE", longRestAmount: "Recover spent Hit Dice up to half total character Hit Dice, minimum 1", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.1", scope: "Core rest", className: "Monk", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d8", capacityBasis: "1 die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Dice; heal die + CON (minimum 0)", longRestMode: "REGAIN_HALF_HIT_DICE", longRestAmount: "Recover spent Hit Dice up to half total character Hit Dice, minimum 1", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.1", scope: "Core rest", className: "Paladin", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d10", capacityBasis: "1 die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Dice; heal die + CON (minimum 0)", longRestMode: "REGAIN_HALF_HIT_DICE", longRestAmount: "Recover spent Hit Dice up to half total character Hit Dice, minimum 1", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.1", scope: "Core rest", className: "Ranger", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d10", capacityBasis: "1 die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Dice; heal die + CON (minimum 0)", longRestMode: "REGAIN_HALF_HIT_DICE", longRestAmount: "Recover spent Hit Dice up to half total character Hit Dice, minimum 1", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.1", scope: "Core rest", className: "Rogue", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d8", capacityBasis: "1 die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Dice; heal die + CON (minimum 0)", longRestMode: "REGAIN_HALF_HIT_DICE", longRestAmount: "Recover spent Hit Dice up to half total character Hit Dice, minimum 1", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.1", scope: "Core rest", className: "Sorcerer", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d6", capacityBasis: "1 die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Dice; heal die + CON (minimum 0)", longRestMode: "REGAIN_HALF_HIT_DICE", longRestAmount: "Recover spent Hit Dice up to half total character Hit Dice, minimum 1", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.1", scope: "Core rest", className: "Warlock", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d8", capacityBasis: "1 die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Dice; heal die + CON (minimum 0)", longRestMode: "REGAIN_HALF_HIT_DICE", longRestAmount: "Recover spent Hit Dice up to half total character Hit Dice, minimum 1", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.1", scope: "Core rest", className: "Wizard", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d6", capacityBasis: "1 die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Dice; heal die + CON (minimum 0)", longRestMode: "REGAIN_HALF_HIT_DICE", longRestAmount: "Recover spent Hit Dice up to half total character Hit Dice, minimum 1", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.2.1", scope: "Core rest", className: "Barbarian", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d12", capacityBasis: "1 Hit Point Die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Point Dice; heal die + CON (minimum 1 HP)", longRestMode: "REGAIN_ALL_HIT_DICE", longRestAmount: "Recover all spent Hit Point Dice", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.2.1", scope: "Core rest", className: "Bard", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d8", capacityBasis: "1 Hit Point Die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Point Dice; heal die + CON (minimum 1 HP)", longRestMode: "REGAIN_ALL_HIT_DICE", longRestAmount: "Recover all spent Hit Point Dice", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.2.1", scope: "Core rest", className: "Cleric", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d8", capacityBasis: "1 Hit Point Die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Point Dice; heal die + CON (minimum 1 HP)", longRestMode: "REGAIN_ALL_HIT_DICE", longRestAmount: "Recover all spent Hit Point Dice", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.2.1", scope: "Core rest", className: "Druid", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d8", capacityBasis: "1 Hit Point Die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Point Dice; heal die + CON (minimum 1 HP)", longRestMode: "REGAIN_ALL_HIT_DICE", longRestAmount: "Recover all spent Hit Point Dice", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.2.1", scope: "Core rest", className: "Fighter", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d10", capacityBasis: "1 Hit Point Die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Point Dice; heal die + CON (minimum 1 HP)", longRestMode: "REGAIN_ALL_HIT_DICE", longRestAmount: "Recover all spent Hit Point Dice", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.2.1", scope: "Core rest", className: "Monk", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d8", capacityBasis: "1 Hit Point Die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Point Dice; heal die + CON (minimum 1 HP)", longRestMode: "REGAIN_ALL_HIT_DICE", longRestAmount: "Recover all spent Hit Point Dice", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.2.1", scope: "Core rest", className: "Paladin", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d10", capacityBasis: "1 Hit Point Die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Point Dice; heal die + CON (minimum 1 HP)", longRestMode: "REGAIN_ALL_HIT_DICE", longRestAmount: "Recover all spent Hit Point Dice", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.2.1", scope: "Core rest", className: "Ranger", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d10", capacityBasis: "1 Hit Point Die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Point Dice; heal die + CON (minimum 1 HP)", longRestMode: "REGAIN_ALL_HIT_DICE", longRestAmount: "Recover all spent Hit Point Dice", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.2.1", scope: "Core rest", className: "Rogue", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d8", capacityBasis: "1 Hit Point Die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Point Dice; heal die + CON (minimum 1 HP)", longRestMode: "REGAIN_ALL_HIT_DICE", longRestAmount: "Recover all spent Hit Point Dice", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.2.1", scope: "Core rest", className: "Sorcerer", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d6", capacityBasis: "1 Hit Point Die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Point Dice; heal die + CON (minimum 1 HP)", longRestMode: "REGAIN_ALL_HIT_DICE", longRestAmount: "Recover all spent Hit Point Dice", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.2.1", scope: "Core rest", className: "Warlock", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d8", capacityBasis: "1 Hit Point Die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Point Dice; heal die + CON (minimum 1 HP)", longRestMode: "REGAIN_ALL_HIT_DICE", longRestAmount: "Recover all spent Hit Point Dice", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.2.1", scope: "Core rest", className: "Wizard", subclassName: "", resource: "Hit Dice", minLevel: 1, hitDie: "d6", capacityBasis: "1 Hit Point Die per level in this class; multiclass pools stay separate", shortRestMode: "SPEND_OWN_HIT_DICE", shortRestAmount: "Spend remaining actor-owned Hit Point Dice; heal die + CON (minimum 1 HP)", longRestMode: "REGAIN_ALL_HIT_DICE", longRestAmount: "Recover all spent Hit Point Dice", oncePerLongRest: false, engineKind: "hit_dice", notes: "Never combine actors or multiclass die types into a shared party bucket." },
  { ruleset: "5.1", scope: "Class", className: "Barbarian", subclassName: "", resource: "Rage", minLevel: 1, hitDie: "d12", capacityBasis: "Uses by Barbarian level", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "REGAIN_ALL", longRestAmount: "All expended uses", oncePerLongRest: false, engineKind: "class_pool", notes: "2014 Rage is Long-Rest only." },
  { ruleset: "5.1", scope: "Class", className: "Bard", subclassName: "", resource: "Bardic Inspiration — Font of Inspiration", minLevel: 5, hitDie: "d8", capacityBasis: "Uses = CHA modifier, minimum 1", shortRestMode: "REGAIN_ALL", shortRestAmount: "All expended uses", longRestMode: "REGAIN_ALL", longRestAmount: "All expended uses", oncePerLongRest: false, engineKind: "class_pool", notes: "Before Bard 5, Bardic Inspiration is Long-Rest only." },
  { ruleset: "5.1", scope: "Class", className: "Bard", subclassName: "", resource: "Song of Rest", minLevel: 2, hitDie: "d8", capacityBasis: "Per eligible creature that spends 1+ Hit Dice", shortRestMode: "REST_HEALING_BONUS", shortRestAmount: "Extra d6; d8 at Bard 9; d10 at 13; d12 at 17", longRestMode: "NONE", longRestAmount: "0", oncePerLongRest: false, engineKind: "rest_healing_bonus", notes: "Adds Short-Rest healing; it is not a refreshable pool." },
  { ruleset: "5.1", scope: "Class", className: "Cleric", subclassName: "", resource: "Channel Divinity", minLevel: 2, hitDie: "d8", capacityBasis: "Uses by Cleric level", shortRestMode: "REGAIN_ALL", shortRestAmount: "All expended uses", longRestMode: "REGAIN_ALL", longRestAmount: "All expended uses", oncePerLongRest: false, engineKind: "class_pool", notes: "2014 fully refreshes on Short Rest." },
  { ruleset: "5.1", scope: "Class", className: "Druid", subclassName: "", resource: "Wild Shape", minLevel: 2, hitDie: "d8", capacityBasis: "2 uses", shortRestMode: "REGAIN_ALL", shortRestAmount: "All expended uses", longRestMode: "REGAIN_ALL", longRestAmount: "All expended uses", oncePerLongRest: false, engineKind: "class_pool", notes: "2014 fully refreshes on Short Rest." },
  { ruleset: "5.1", scope: "Subclass", className: "Druid", subclassName: "Circle of the Land", resource: "Natural Recovery", minLevel: 2, hitDie: "d8", capacityBasis: "Recovered spell-slot levels", shortRestMode: "RECOVER_SLOT_LEVELS", shortRestAmount: "Combined slot levels &lt;= ceil(Druid level/2); no level 6+ slot", longRestMode: "RESET_GATE", longRestAmount: "Feature becomes available again after Long Rest", oncePerLongRest: true, engineKind: "spell_slot_recovery", notes: "One Short-Rest recovery use between Long Rests." },
  { ruleset: "5.1", scope: "Class", className: "Fighter", subclassName: "", resource: "Second Wind", minLevel: 1, hitDie: "d10", capacityBasis: "1 use", shortRestMode: "REGAIN_ALL", shortRestAmount: "Regain expended use", longRestMode: "REGAIN_ALL", longRestAmount: "Regain expended use", oncePerLongRest: false, engineKind: "class_pool", notes: "2014 one-use pool." },
  { ruleset: "5.1", scope: "Class", className: "Fighter", subclassName: "", resource: "Action Surge", minLevel: 2, hitDie: "d10", capacityBasis: "1 use through level 16", shortRestMode: "REGAIN_ALL", shortRestAmount: "All expended uses", longRestMode: "REGAIN_ALL", longRestAmount: "All expended uses", oncePerLongRest: false, engineKind: "class_pool", notes: "One use in Broken Chain's 1–16 curve." },
  { ruleset: "5.1", scope: "Class", className: "Monk", subclassName: "", resource: "Ki", minLevel: 2, hitDie: "d8", capacityBasis: "Ki points = Monk level", shortRestMode: "REGAIN_ALL", shortRestAmount: "All expended Ki; at least 30 minutes meditation during rest", longRestMode: "REGAIN_ALL", longRestAmount: "All expended Ki", oncePerLongRest: false, engineKind: "class_pool", notes: "2014 terminology is Ki." },
  { ruleset: "5.1", scope: "Class", className: "Paladin", subclassName: "", resource: "Channel Divinity", minLevel: 3, hitDie: "d10", capacityBasis: "Uses by Paladin level", shortRestMode: "REGAIN_ALL", shortRestAmount: "All expended uses", longRestMode: "REGAIN_ALL", longRestAmount: "All expended uses", oncePerLongRest: false, engineKind: "class_pool", notes: "2014 fully refreshes on Short Rest." },
  { ruleset: "5.1", scope: "Class", className: "Ranger", subclassName: "", resource: "No class-specific Short-Rest resource", minLevel: 1, hitDie: "d10", capacityBasis: "", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "NONE", longRestAmount: "Spell slots recover on Long Rest", oncePerLongRest: false, engineKind: "none", notes: "Hit Dice still use the core rest row." },
  { ruleset: "5.1", scope: "Class", className: "Rogue", subclassName: "", resource: "No class-specific Short-Rest resource", minLevel: 1, hitDie: "d8", capacityBasis: "", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "NONE", longRestAmount: "", oncePerLongRest: false, engineKind: "none", notes: "Hit Dice still use the core rest row." },
  { ruleset: "5.1", scope: "Class", className: "Sorcerer", subclassName: "", resource: "Sorcery Points", minLevel: 2, hitDie: "d6", capacityBasis: "Sorcery Points = Sorcerer level", shortRestMode: "NONE", shortRestAmount: "0 through Sorcerer 19", longRestMode: "REGAIN_ALL", longRestAmount: "All spent Sorcery Points", oncePerLongRest: false, engineKind: "class_pool", notes: "No Short-Rest Sorcery Point recovery in levels 1–16." },
  { ruleset: "5.1", scope: "Class", className: "Sorcerer", subclassName: "", resource: "Sorcerous Restoration", minLevel: 20, hitDie: "d6", capacityBasis: "Fixed", shortRestMode: "REGAIN_FIXED", shortRestAmount: "4 Sorcery Points", longRestMode: "REGAIN_ALL", longRestAmount: "Normal Long-Rest Sorcery Point recovery", oncePerLongRest: false, engineKind: "class_pool", notes: "Outside 1–16; retained so the SRD table stays correct." },
  { ruleset: "5.1", scope: "Class", className: "Warlock", subclassName: "", resource: "Pact Magic", minLevel: 1, hitDie: "d8", capacityBasis: "Pact slots by Warlock level", shortRestMode: "REGAIN_ALL", shortRestAmount: "All expended Pact Magic slots", longRestMode: "REGAIN_ALL", longRestAmount: "All expended Pact Magic slots", oncePerLongRest: false, engineKind: "pact_slots", notes: "Never merge Pact slots with multiclass shared spell slots." },
  { ruleset: "5.1", scope: "Subclass", className: "Warlock", subclassName: "The Fiend", resource: "Dark One's Own Luck", minLevel: 6, hitDie: "d8", capacityBasis: "1 use", shortRestMode: "REGAIN_ALL", shortRestAmount: "Regain expended use", longRestMode: "REGAIN_ALL", longRestAmount: "Regain expended use", oncePerLongRest: false, engineKind: "subclass_pool", notes: "Edition trap: SR/LR in 5.1, Long-Rest only in 5.2.1." },
  { ruleset: "5.1", scope: "Class", className: "Wizard", subclassName: "", resource: "Arcane Recovery", minLevel: 1, hitDie: "d6", capacityBasis: "Recovered spell-slot levels", shortRestMode: "RECOVER_SLOT_LEVELS", shortRestAmount: "Once per day after SR: combined levels &lt;= ceil(Wizard level/2); no level 6+ slot", longRestMode: "RESET_GATE", longRestAmount: "Normal spell slots recover on Long Rest", oncePerLongRest: true, engineKind: "spell_slot_recovery", notes: "2014 wording is once per day." },
  { ruleset: "5.2.1", scope: "Class", className: "Barbarian", subclassName: "", resource: "Rage", minLevel: 1, hitDie: "d12", capacityBasis: "Uses by Barbarian level", shortRestMode: "REGAIN_ONE", shortRestAmount: "1 expended use", longRestMode: "REGAIN_ALL", longRestAmount: "All expended uses", oncePerLongRest: false, engineKind: "class_pool", notes: "5.2.1 adds one Rage on Short Rest." },
  { ruleset: "5.2.1", scope: "Class", className: "Bard", subclassName: "", resource: "Bardic Inspiration — Font of Inspiration", minLevel: 5, hitDie: "d8", capacityBasis: "Uses = CHA modifier, minimum 1", shortRestMode: "REGAIN_ALL", shortRestAmount: "All expended uses", longRestMode: "REGAIN_ALL", longRestAmount: "All expended uses", oncePerLongRest: false, engineKind: "class_pool", notes: "Before Bard 5, Bardic Inspiration is Long-Rest only." },
  { ruleset: "5.2.1", scope: "Class", className: "Cleric", subclassName: "", resource: "Channel Divinity", minLevel: 2, hitDie: "d8", capacityBasis: "Uses by Cleric level", shortRestMode: "REGAIN_ONE", shortRestAmount: "1 expended use", longRestMode: "REGAIN_ALL", longRestAmount: "All expended uses", oncePerLongRest: false, engineKind: "class_pool", notes: "Do not use the 5.1 full-SR refresh." },
  { ruleset: "5.2.1", scope: "Class", className: "Druid", subclassName: "", resource: "Wild Shape", minLevel: 2, hitDie: "d8", capacityBasis: "Uses by Druid level", shortRestMode: "REGAIN_ONE", shortRestAmount: "1 expended use", longRestMode: "REGAIN_ALL", longRestAmount: "All expended uses", oncePerLongRest: false, engineKind: "class_pool", notes: "Do not use the 5.1 full-SR refresh." },
  { ruleset: "5.2.1", scope: "Subclass", className: "Druid", subclassName: "Circle of the Land", resource: "Natural Recovery", minLevel: 6, hitDie: "d8", capacityBasis: "Recovered spell-slot levels", shortRestMode: "RECOVER_SLOT_LEVELS", shortRestAmount: "Combined slot levels &lt;= ceil(Druid level/2); no level 6+ slot", longRestMode: "RESET_GATE", longRestAmount: "Feature becomes available again after Long Rest", oncePerLongRest: true, engineKind: "spell_slot_recovery", notes: "One Short-Rest recovery use between Long Rests." },
  { ruleset: "5.2.1", scope: "Class", className: "Fighter", subclassName: "", resource: "Second Wind", minLevel: 1, hitDie: "d10", capacityBasis: "Uses by Fighter level", shortRestMode: "REGAIN_ONE", shortRestAmount: "1 expended use", longRestMode: "REGAIN_ALL", longRestAmount: "All expended uses", oncePerLongRest: false, engineKind: "class_pool", notes: "At Fighter 7 the pool is 3, but only one returns on SR." },
  { ruleset: "5.2.1", scope: "Class", className: "Fighter", subclassName: "", resource: "Action Surge", minLevel: 2, hitDie: "d10", capacityBasis: "1 use through level 16", shortRestMode: "REGAIN_ALL", shortRestAmount: "All expended uses", longRestMode: "REGAIN_ALL", longRestAmount: "All expended uses", oncePerLongRest: false, engineKind: "class_pool", notes: "One use in Broken Chain's 1–16 curve." },
  { ruleset: "5.2.1", scope: "Class", className: "Monk", subclassName: "", resource: "Focus Points", minLevel: 2, hitDie: "d8", capacityBasis: "Focus Points = Monk level", shortRestMode: "REGAIN_ALL", shortRestAmount: "All expended Focus Points", longRestMode: "REGAIN_ALL", longRestAmount: "All expended Focus Points", oncePerLongRest: false, engineKind: "class_pool", notes: "5.2.1 terminology is Focus Points." },
  { ruleset: "5.2.1", scope: "Class", className: "Paladin", subclassName: "", resource: "Channel Divinity", minLevel: 3, hitDie: "d10", capacityBasis: "Uses by Paladin level", shortRestMode: "REGAIN_ONE", shortRestAmount: "1 expended use", longRestMode: "REGAIN_ALL", longRestAmount: "All expended uses", oncePerLongRest: false, engineKind: "class_pool", notes: "At Paladin 7 the pool is 2; SR returns one." },
  { ruleset: "5.2.1", scope: "Class", className: "Ranger", subclassName: "", resource: "Favored Enemy — free Hunter's Mark casts", minLevel: 1, hitDie: "d10", capacityBasis: "Uses by Ranger level", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "REGAIN_ALL", longRestAmount: "All expended free casts", oncePerLongRest: false, engineKind: "class_pool", notes: "Long-Rest only; do not restore these on SR." },
  { ruleset: "5.2.1", scope: "Class", className: "Rogue", subclassName: "", resource: "No class-specific Short-Rest resource", minLevel: 1, hitDie: "d8", capacityBasis: "", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "NONE", longRestAmount: "", oncePerLongRest: false, engineKind: "none", notes: "Hit Dice still use the core rest row." },
  { ruleset: "5.2.1", scope: "Class", className: "Sorcerer", subclassName: "", resource: "Sorcery Points", minLevel: 2, hitDie: "d6", capacityBasis: "Sorcery Points = Sorcerer level", shortRestMode: "CONDITIONAL", shortRestAmount: "Use Sorcerous Restoration from Sorcerer 5; otherwise 0", longRestMode: "REGAIN_ALL", longRestAmount: "All spent Sorcery Points", oncePerLongRest: false, engineKind: "class_pool", notes: "Base pool is Long-Rest recovery." },
  { ruleset: "5.2.1", scope: "Class", className: "Sorcerer", subclassName: "", resource: "Sorcerous Restoration", minLevel: 5, hitDie: "d6", capacityBasis: "Recovered Sorcery Points", shortRestMode: "REGAIN_FORMULA", shortRestAmount: "Up to floor(Sorcerer level/2) expended Sorcery Points", longRestMode: "RESET_GATE", longRestAmount: "Feature becomes available again after Long Rest", oncePerLongRest: true, engineKind: "class_pool", notes: "One use between Long Rests." },
  { ruleset: "5.2.1", scope: "Class", className: "Warlock", subclassName: "", resource: "Pact Magic", minLevel: 1, hitDie: "d8", capacityBasis: "Pact slots by Warlock level", shortRestMode: "REGAIN_ALL", shortRestAmount: "All expended Pact Magic slots", longRestMode: "REGAIN_ALL", longRestAmount: "All expended Pact Magic slots", oncePerLongRest: false, engineKind: "pact_slots", notes: "Actor-owned Pact slots only." },
  { ruleset: "5.2.1", scope: "Subclass", className: "Warlock", subclassName: "Fiend Patron", resource: "Dark One's Own Luck", minLevel: 6, hitDie: "d8", capacityBasis: "Uses = CHA modifier, minimum 1", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "REGAIN_ALL", longRestAmount: "All expended uses", oncePerLongRest: false, engineKind: "subclass_pool", notes: "Edition trap: Long-Rest only in 5.2.1." },
  { ruleset: "5.2.1", scope: "Class", className: "Wizard", subclassName: "", resource: "Arcane Recovery", minLevel: 1, hitDie: "d6", capacityBasis: "Recovered spell-slot levels", shortRestMode: "RECOVER_SLOT_LEVELS", shortRestAmount: "Combined levels &lt;= ceil(Wizard level/2); no level 6+ slot", longRestMode: "RESET_GATE", longRestAmount: "Feature becomes available again after Long Rest", oncePerLongRest: true, engineKind: "spell_slot_recovery", notes: "Once used, unavailable until Long Rest." },
];

export const SPECIES_RECOVERY: readonly SpeciesRecoveryRule[] = [
  { ruleset: "5.1", terminology: "Race", species: "Dwarf", resource: "No limited SR racial pool", minLevel: 1, capacityBasis: "", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "NONE", longRestAmount: "", engineKind: "none", notes: "2014 Stonecunning is not a recharge pool." },
  { ruleset: "5.1", terminology: "Race", species: "Elf", resource: "No limited SR racial pool", minLevel: 1, capacityBasis: "", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "NONE", longRestAmount: "", engineKind: "none", notes: "Trance is not a resource refresh pool." },
  { ruleset: "5.1", terminology: "Race", species: "Halfling", resource: "No limited SR racial pool", minLevel: 1, capacityBasis: "", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "NONE", longRestAmount: "", engineKind: "none", notes: "" },
  { ruleset: "5.1", terminology: "Race", species: "Human", resource: "No limited SR racial pool", minLevel: 1, capacityBasis: "", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "NONE", longRestAmount: "", engineKind: "none", notes: "" },
  { ruleset: "5.1", terminology: "Race", species: "Dragonborn", resource: "Breath Weapon", minLevel: 1, capacityBasis: "1 use", shortRestMode: "REGAIN_ALL", shortRestAmount: "Regain expended use", longRestMode: "REGAIN_ALL", longRestAmount: "Regain expended use", engineKind: "species_pool", notes: "2014 Breath Weapon refreshes on Short OR Long Rest." },
  { ruleset: "5.1", terminology: "Race", species: "Gnome", resource: "No limited SR racial pool", minLevel: 1, capacityBasis: "", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "NONE", longRestAmount: "", engineKind: "none", notes: "" },
  { ruleset: "5.1", terminology: "Race", species: "Half-Elf", resource: "No limited SR racial pool", minLevel: 1, capacityBasis: "", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "NONE", longRestAmount: "", engineKind: "none", notes: "" },
  { ruleset: "5.1", terminology: "Race", species: "Half-Orc", resource: "Relentless Endurance", minLevel: 1, capacityBasis: "1 use", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "REGAIN_ALL", longRestAmount: "Regain expended use", engineKind: "species_pool", notes: "Long-Rest only." },
  { ruleset: "5.1", terminology: "Race", species: "Tiefling", resource: "Infernal Legacy free spell casts", minLevel: 3, capacityBasis: "Hellish Rebuke 1/LR; Darkness 1/LR at level 5", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "REGAIN_ALL", longRestAmount: "Each expended free cast returns", engineKind: "species_free_cast", notes: "Long-Rest only." },
  { ruleset: "5.2.1", terminology: "Species", species: "Dragonborn", resource: "Breath Weapon", minLevel: 1, capacityBasis: "Uses = Proficiency Bonus", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "REGAIN_ALL", longRestAmount: "All expended uses", engineKind: "species_pool", notes: "5.2.1 Breath Weapon is Long-Rest only." },
  { ruleset: "5.2.1", terminology: "Species", species: "Dragonborn", resource: "Draconic Flight", minLevel: 5, capacityBasis: "1 use", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "REGAIN_ALL", longRestAmount: "Regain expended use", engineKind: "species_pool", notes: "Long-Rest only." },
  { ruleset: "5.2.1", terminology: "Species", species: "Dwarf", resource: "Stonecunning", minLevel: 1, capacityBasis: "Uses = Proficiency Bonus", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "REGAIN_ALL", longRestAmount: "All expended uses", engineKind: "species_pool", notes: "Long-Rest only." },
  { ruleset: "5.2.1", terminology: "Species", species: "Elf", resource: "Elven Lineage free spell casts", minLevel: 3, capacityBasis: "Granted level 3/5 spell: 1 free cast each", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "REGAIN_ALL", longRestAmount: "Each expended free cast returns", engineKind: "species_free_cast", notes: "Long-Rest only; rest-time cantrip swaps are not recovery pools." },
  { ruleset: "5.2.1", terminology: "Species", species: "Gnome", resource: "Forest Gnome — Speak with Animals free casts", minLevel: 1, capacityBasis: "Uses = Proficiency Bonus", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "REGAIN_ALL", longRestAmount: "All expended uses", engineKind: "species_free_cast", notes: "Long-Rest only." },
  { ruleset: "5.2.1", terminology: "Species", species: "Goliath", resource: "Giant Ancestry", minLevel: 1, capacityBasis: "Uses = Proficiency Bonus", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "REGAIN_ALL", longRestAmount: "All expended uses", engineKind: "species_pool", notes: "Long-Rest only." },
  { ruleset: "5.2.1", terminology: "Species", species: "Goliath", resource: "Large Form", minLevel: 5, capacityBasis: "1 use", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "REGAIN_ALL", longRestAmount: "Regain expended use", engineKind: "species_pool", notes: "Long-Rest only." },
  { ruleset: "5.2.1", terminology: "Species", species: "Halfling", resource: "No limited SR species pool", minLevel: 1, capacityBasis: "", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "NONE", longRestAmount: "", engineKind: "none", notes: "" },
  { ruleset: "5.2.1", terminology: "Species", species: "Human", resource: "Resourceful — Heroic Inspiration", minLevel: 1, capacityBasis: "Grant 1 Heroic Inspiration", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "GRANT_ON_LONG_REST", longRestAmount: "Gain Heroic Inspiration", engineKind: "species_pool", notes: "Long-Rest only." },
  { ruleset: "5.2.1", terminology: "Species", species: "Orc", resource: "Adrenaline Rush", minLevel: 1, capacityBasis: "Uses = Proficiency Bonus", shortRestMode: "REGAIN_ALL", shortRestAmount: "All expended uses", longRestMode: "REGAIN_ALL", longRestAmount: "All expended uses", engineKind: "species_pool", notes: "At levels 5–8, PB 3 means all 3 uses return on SR." },
  { ruleset: "5.2.1", terminology: "Species", species: "Orc", resource: "Relentless Endurance", minLevel: 1, capacityBasis: "1 use", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "REGAIN_ALL", longRestAmount: "Regain expended use", engineKind: "species_pool", notes: "Long-Rest only." },
  { ruleset: "5.2.1", terminology: "Species", species: "Tiefling", resource: "Fiendish Legacy free spell casts", minLevel: 3, capacityBasis: "Granted level 3/5 spell: 1 free cast each", shortRestMode: "NONE", shortRestAmount: "0", longRestMode: "REGAIN_ALL", longRestAmount: "Each expended free cast returns", engineKind: "species_free_cast", notes: "Long-Rest only." },
];

const norm = (s: string | null | undefined) => (s ?? "").trim().toLowerCase();

/**
 * Every recovery rule that applies to a class at a level, its subclass rules included.
 *
 * ⚠ A SUBCLASS RULE IS ADDITIVE, NEVER AN OVERRIDE — the same contract the older registry states.
 */
export function classRecoveryFor(
  ruleset: "5.2.1" | "5.1",
  className: string,
  subclassName: string | null | undefined,
  level: number,
): ClassRecoveryRule[] {
  const cls = norm(className);
  const sub = norm(subclassName);
  return CLASS_RECOVERY.filter(r =>
    r.ruleset === ruleset
    && norm(r.className) === cls
    && (!r.subclassName || norm(r.subclassName) === sub)
    && level >= r.minLevel);
}

/**
 * ⚠ POOLS ONLY. A row whose `engineKind` is "none" says the species was CHECKED and grants
 * nothing — an answer, not a hole — and must not surface as a pool the sheet is missing.
 */
export function speciesRecoveryFor(
  ruleset: "5.2.1" | "5.1",
  species: string | undefined,
  level: number,
): SpeciesRecoveryRule[] {
  const name = norm(species);
  if (!name) return [];
  return SPECIES_RECOVERY.filter(r =>
    r.ruleset === ruleset
    && norm(r.species) === name
    && level >= r.minLevel
    && r.engineKind !== ""
    && r.engineKind !== "none");
}
