/**
 * SHORT REST RULES — the D&D mod's copy of the workbook's class and subclass recovery authority.
 *
 * ⚠ GENERATED from `broken_chain_encounter_checker_V3_2_4096_actor_first_balanced_center.xlsx`
 * (sheet "Short Rest Rules") by `scripts/gen-short-rest-rules.mjs`. Do not hand-edit.
 *
 * ⚠ THIS IS MOD CONTENT, NOT ENGINE. A short rest is a 5e concept; the engine must not learn what
 * one is. The SHAPE — a pool that refreshes on a named cadence — is engine, and lives in
 * `core/types/tabs.ts`. Same split `featPricing.generated.ts` and `contentScope.ts` carry.
 *
 * ── WHY IT EXISTS, IN THE SHEET'S OWN WORDS ─────────────────────────────────────────────────
 *   *"The app reads this compact authority to resolve the actual actor it is showing. The external
 *   party runtime applies these rules to live state; the workbook does not simulate the 1,024
 *   parties or substitute a generic 25% recovery."*
 *
 * The app is that external runtime. `partyResourceCurve.SHORT_REST_RECOVERY` is the generic that
 * sentence rules out, and Runtime Inputs B11 disables it outright: *"Short Rest Recovery | 0 |
 * Disabled generic fallback; resolve actual Hit Dice and named actor rules"*.
 *
 * ── COVERAGE ────────────────────────────────────────────────────────────────────────────────
 *   168 rules · 33 class · 135 subclass · 16 classes
 *   recovery tokens: Spend one at a time until current maximum HP is reached or no dice remain., actor_chosen_legal_slot_levels_up_to_half_wizard_level, all_expended_uses, one_expended_use, up_to_half_class_level_rounded_down
 *   timings: during_short_rest, on_finish_short_rest
 */

/** Where the rule is attached. A subclass rule is additive to its class rules, never a override. */
export type ShortRestScope = "class" | "subclass";

export type ShortRestRule = {
  /** The workbook's own lookup key, e.g. `class:Fighter:—:2`. Stable across regenerations. */
  key: string;
  scope: ShortRestScope;
  className: string;
  /** null on a class-scoped rule. */
  subclassName: string | null;
  /** The pool as printed: "Action Surge", "Pact Magic slots", "Hit Point Dice". */
  resource: string;
  /** First class level that grants it; null where the sheet leaves it blank. */
  earliestLevel: number | null;
  /**
   * How much comes back. A token where the sheet gives one — `all_expended_uses`,
   * `one_expended_use`, `up_to_half_class_level_rounded_down` — and prose for Hit Point Dice,
   * whose amount is a player decision rather than a fixed quantity.
   */
  recovery: string | null;
  /** `during_short_rest` (spent as part of it) vs `on_finish_short_rest` (refreshed after). */
  timing: string | null;
  /** `each_short_rest`, `each_legal_short_rest`, `once_per_long_rest`. */
  useLimit: string | null;
  registryStatus: string;
};

/**
 * ⚠ A ROW SAYING "none" IS AN ANSWER, NOT A HOLE. Most subclasses grant no short-rest resource of
 * their own, and the sheet records that explicitly rather than omitting the row. Dropping them
 * would turn "this subclass was checked and has nothing" into "this subclass was never checked".
 */
export const SHORT_REST_RULES: readonly ShortRestRule[] = [
  {
    key: "class:Artificer:hit-point-dice",
    scope: "class",
    className: "Artificer",
    subclassName: null,
    resource: "Hit Point Dice",
    earliestLevel: 1,
    recovery: "Spend one at a time until current maximum HP is reached or no dice remain.",
    timing: "during_short_rest",
    useLimit: "each_legal_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Artificer:—:none",
    scope: "class",
    className: "Artificer",
    subclassName: null,
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Barbarian:hit-point-dice",
    scope: "class",
    className: "Barbarian",
    subclassName: null,
    resource: "Hit Point Dice",
    earliestLevel: 1,
    recovery: "Spend one at a time until current maximum HP is reached or no dice remain.",
    timing: "during_short_rest",
    useLimit: "each_legal_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Barbarian:—:1",
    scope: "class",
    className: "Barbarian",
    subclassName: null,
    resource: "Rage",
    earliestLevel: 1,
    recovery: "one_expended_use",
    timing: "on_finish_short_rest",
    useLimit: "each_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Bard:hit-point-dice",
    scope: "class",
    className: "Bard",
    subclassName: null,
    resource: "Hit Point Dice",
    earliestLevel: 1,
    recovery: "Spend one at a time until current maximum HP is reached or no dice remain.",
    timing: "during_short_rest",
    useLimit: "each_legal_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Bard:—:1",
    scope: "class",
    className: "Bard",
    subclassName: null,
    resource: "Bardic Inspiration",
    earliestLevel: 5,
    recovery: "all_expended_uses",
    timing: "on_finish_short_rest",
    useLimit: "each_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Blood Hunter:hit-point-dice",
    scope: "class",
    className: "Blood Hunter",
    subclassName: null,
    resource: "Hit Point Dice",
    earliestLevel: 1,
    recovery: "Spend one at a time until current maximum HP is reached or no dice remain.",
    timing: "during_short_rest",
    useLimit: "each_legal_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Blood Hunter:—:none",
    scope: "class",
    className: "Blood Hunter",
    subclassName: null,
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Cleric:hit-point-dice",
    scope: "class",
    className: "Cleric",
    subclassName: null,
    resource: "Hit Point Dice",
    earliestLevel: 1,
    recovery: "Spend one at a time until current maximum HP is reached or no dice remain.",
    timing: "during_short_rest",
    useLimit: "each_legal_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Cleric:—:1",
    scope: "class",
    className: "Cleric",
    subclassName: null,
    resource: "Channel Divinity",
    earliestLevel: 2,
    recovery: "one_expended_use",
    timing: "on_finish_short_rest",
    useLimit: "each_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Druid:hit-point-dice",
    scope: "class",
    className: "Druid",
    subclassName: null,
    resource: "Hit Point Dice",
    earliestLevel: 1,
    recovery: "Spend one at a time until current maximum HP is reached or no dice remain.",
    timing: "during_short_rest",
    useLimit: "each_legal_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Druid:—:1",
    scope: "class",
    className: "Druid",
    subclassName: null,
    resource: "Wild Shape",
    earliestLevel: 2,
    recovery: "one_expended_use",
    timing: "on_finish_short_rest",
    useLimit: "each_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Fighter:hit-point-dice",
    scope: "class",
    className: "Fighter",
    subclassName: null,
    resource: "Hit Point Dice",
    earliestLevel: 1,
    recovery: "Spend one at a time until current maximum HP is reached or no dice remain.",
    timing: "during_short_rest",
    useLimit: "each_legal_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Fighter:—:1",
    scope: "class",
    className: "Fighter",
    subclassName: null,
    resource: "Second Wind",
    earliestLevel: 1,
    recovery: "one_expended_use",
    timing: "on_finish_short_rest",
    useLimit: "each_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Fighter:—:2",
    scope: "class",
    className: "Fighter",
    subclassName: null,
    resource: "Action Surge",
    earliestLevel: 2,
    recovery: "all_expended_uses",
    timing: "on_finish_short_rest",
    useLimit: "each_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Gunslinger:hit-point-dice",
    scope: "class",
    className: "Gunslinger",
    subclassName: null,
    resource: "Hit Point Dice",
    earliestLevel: 1,
    recovery: "Spend one at a time until current maximum HP is reached or no dice remain.",
    timing: "during_short_rest",
    useLimit: "each_legal_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Gunslinger:—:1",
    scope: "class",
    className: "Gunslinger",
    subclassName: null,
    resource: "Risk Dice",
    earliestLevel: 1,
    recovery: "all_expended_uses",
    timing: "on_finish_short_rest",
    useLimit: "each_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Illrigger:hit-point-dice",
    scope: "class",
    className: "Illrigger",
    subclassName: null,
    resource: "Hit Point Dice",
    earliestLevel: 1,
    recovery: "Spend one at a time until current maximum HP is reached or no dice remain.",
    timing: "during_short_rest",
    useLimit: "each_legal_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Illrigger:—:none",
    scope: "class",
    className: "Illrigger",
    subclassName: null,
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "NEEDS_EXTENDED_CLASS_SOURCE"
  },
  {
    key: "class:Monk:hit-point-dice",
    scope: "class",
    className: "Monk",
    subclassName: null,
    resource: "Hit Point Dice",
    earliestLevel: 1,
    recovery: "Spend one at a time until current maximum HP is reached or no dice remain.",
    timing: "during_short_rest",
    useLimit: "each_legal_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Monk:—:1",
    scope: "class",
    className: "Monk",
    subclassName: null,
    resource: "Focus Points",
    earliestLevel: 2,
    recovery: "all_expended_uses",
    timing: "on_finish_short_rest",
    useLimit: "each_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Paladin:hit-point-dice",
    scope: "class",
    className: "Paladin",
    subclassName: null,
    resource: "Hit Point Dice",
    earliestLevel: 1,
    recovery: "Spend one at a time until current maximum HP is reached or no dice remain.",
    timing: "during_short_rest",
    useLimit: "each_legal_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Paladin:—:1",
    scope: "class",
    className: "Paladin",
    subclassName: null,
    resource: "Channel Divinity",
    earliestLevel: 3,
    recovery: "one_expended_use",
    timing: "on_finish_short_rest",
    useLimit: "each_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Ranger:hit-point-dice",
    scope: "class",
    className: "Ranger",
    subclassName: null,
    resource: "Hit Point Dice",
    earliestLevel: 1,
    recovery: "Spend one at a time until current maximum HP is reached or no dice remain.",
    timing: "during_short_rest",
    useLimit: "each_legal_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Ranger:—:none",
    scope: "class",
    className: "Ranger",
    subclassName: null,
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Rogue:hit-point-dice",
    scope: "class",
    className: "Rogue",
    subclassName: null,
    resource: "Hit Point Dice",
    earliestLevel: 1,
    recovery: "Spend one at a time until current maximum HP is reached or no dice remain.",
    timing: "during_short_rest",
    useLimit: "each_legal_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Rogue:—:none",
    scope: "class",
    className: "Rogue",
    subclassName: null,
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Sorcerer:hit-point-dice",
    scope: "class",
    className: "Sorcerer",
    subclassName: null,
    resource: "Hit Point Dice",
    earliestLevel: 1,
    recovery: "Spend one at a time until current maximum HP is reached or no dice remain.",
    timing: "during_short_rest",
    useLimit: "each_legal_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Sorcerer:—:1",
    scope: "class",
    className: "Sorcerer",
    subclassName: null,
    resource: "Sorcery Points (Sorcerous Restoration)",
    earliestLevel: 5,
    recovery: "up_to_half_class_level_rounded_down",
    timing: "on_finish_short_rest",
    useLimit: "once_per_long_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Warlock:hit-point-dice",
    scope: "class",
    className: "Warlock",
    subclassName: null,
    resource: "Hit Point Dice",
    earliestLevel: 1,
    recovery: "Spend one at a time until current maximum HP is reached or no dice remain.",
    timing: "during_short_rest",
    useLimit: "each_legal_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Warlock:—:1",
    scope: "class",
    className: "Warlock",
    subclassName: null,
    resource: "Pact Magic slots",
    earliestLevel: 1,
    recovery: "all_expended_uses",
    timing: "on_finish_short_rest",
    useLimit: "each_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Wizard:hit-point-dice",
    scope: "class",
    className: "Wizard",
    subclassName: null,
    resource: "Hit Point Dice",
    earliestLevel: 1,
    recovery: "Spend one at a time until current maximum HP is reached or no dice remain.",
    timing: "during_short_rest",
    useLimit: "each_legal_short_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "class:Wizard:—:1",
    scope: "class",
    className: "Wizard",
    subclassName: null,
    resource: "Arcane Recovery",
    earliestLevel: 2,
    recovery: "actor_chosen_legal_slot_levels_up_to_half_wizard_level",
    timing: "during_short_rest",
    useLimit: "once_per_long_rest",
    registryStatus: "READY_WOTC_OR_EXTENDED_RULE"
  },
  {
    key: "subclass:Artificer:Alchemist (Forge):none",
    scope: "subclass",
    className: "Artificer",
    subclassName: "Alchemist (Forge)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Artificer:Alchemist (TCoE):none",
    scope: "subclass",
    className: "Artificer",
    subclassName: "Alchemist (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Artificer:Armorer (Forge):none",
    scope: "subclass",
    className: "Artificer",
    subclassName: "Armorer (Forge)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Artificer:Armorer (TCoE):none",
    scope: "subclass",
    className: "Artificer",
    subclassName: "Armorer (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Artificer:Artillerist (Forge):none",
    scope: "subclass",
    className: "Artificer",
    subclassName: "Artillerist (Forge)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Artificer:Artillerist (TCoE):none",
    scope: "subclass",
    className: "Artificer",
    subclassName: "Artillerist (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Artificer:Battle Smith (Forge):none",
    scope: "subclass",
    className: "Artificer",
    subclassName: "Battle Smith (Forge)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Artificer:Battle Smith (TCoE):none",
    scope: "subclass",
    className: "Artificer",
    subclassName: "Battle Smith (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Artificer:Cartographer (Forge):none",
    scope: "subclass",
    className: "Artificer",
    subclassName: "Cartographer (Forge)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Barbarian:Path of the Ancestral Guardian (XGtE):none",
    scope: "subclass",
    className: "Barbarian",
    subclassName: "Path of the Ancestral Guardian (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Barbarian:Path of the Battlerager (SCAG):none",
    scope: "subclass",
    className: "Barbarian",
    subclassName: "Path of the Battlerager (SCAG)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Barbarian:Path of the Beast (TCoE):none",
    scope: "subclass",
    className: "Barbarian",
    subclassName: "Path of the Beast (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Barbarian:Path of the Berserker (2024):none",
    scope: "subclass",
    className: "Barbarian",
    subclassName: "Path of the Berserker (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Barbarian:Path of the Giant (BGG):none",
    scope: "subclass",
    className: "Barbarian",
    subclassName: "Path of the Giant (BGG)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Barbarian:Path of the Storm Herald (XGtE):none",
    scope: "subclass",
    className: "Barbarian",
    subclassName: "Path of the Storm Herald (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Barbarian:Path of the Wild Heart (2024):none",
    scope: "subclass",
    className: "Barbarian",
    subclassName: "Path of the Wild Heart (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Barbarian:Path of the World Tree (2024):none",
    scope: "subclass",
    className: "Barbarian",
    subclassName: "Path of the World Tree (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Barbarian:Path of the Zealot (2024):none",
    scope: "subclass",
    className: "Barbarian",
    subclassName: "Path of the Zealot (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Barbarian:Path of the Zealot (XGtE):none",
    scope: "subclass",
    className: "Barbarian",
    subclassName: "Path of the Zealot (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Barbarian:Path of Wild Magic (TCoE):none",
    scope: "subclass",
    className: "Barbarian",
    subclassName: "Path of Wild Magic (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Bard:College of Creation (TCoE):none",
    scope: "subclass",
    className: "Bard",
    subclassName: "College of Creation (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Bard:College of Dance (2024):none",
    scope: "subclass",
    className: "Bard",
    subclassName: "College of Dance (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Bard:College of Eloquence (TCoE):none",
    scope: "subclass",
    className: "Bard",
    subclassName: "College of Eloquence (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Bard:College of Glamour (2024):none",
    scope: "subclass",
    className: "Bard",
    subclassName: "College of Glamour (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Bard:College of Lore (2024):none",
    scope: "subclass",
    className: "Bard",
    subclassName: "College of Lore (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Bard:College of Spirits (VRGtR):none",
    scope: "subclass",
    className: "Bard",
    subclassName: "College of Spirits (VRGtR)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Bard:College of Swords (XGtE):none",
    scope: "subclass",
    className: "Bard",
    subclassName: "College of Swords (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Bard:College of Valor (2024):none",
    scope: "subclass",
    className: "Bard",
    subclassName: "College of Valor (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Bard:College of Whispers (XGtE):none",
    scope: "subclass",
    className: "Bard",
    subclassName: "College of Whispers (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Blood Hunter:Order of the Ghostslayer:none",
    scope: "subclass",
    className: "Blood Hunter",
    subclassName: "Order of the Ghostslayer",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Blood Hunter:Order of the Lycan:none",
    scope: "subclass",
    className: "Blood Hunter",
    subclassName: "Order of the Lycan",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Blood Hunter:Order of the Mutant:none",
    scope: "subclass",
    className: "Blood Hunter",
    subclassName: "Order of the Mutant",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Blood Hunter:Order of the Profane Soul:none",
    scope: "subclass",
    className: "Blood Hunter",
    subclassName: "Order of the Profane Soul",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Cleric:Arcana Domain (SCAG):none",
    scope: "subclass",
    className: "Cleric",
    subclassName: "Arcana Domain (SCAG)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Cleric:Forge Domain (XGtE):none",
    scope: "subclass",
    className: "Cleric",
    subclassName: "Forge Domain (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Cleric:Grave Domain (XGtE):none",
    scope: "subclass",
    className: "Cleric",
    subclassName: "Grave Domain (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Cleric:Life Domain (2024):none",
    scope: "subclass",
    className: "Cleric",
    subclassName: "Life Domain (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Cleric:Light Domain (2024):none",
    scope: "subclass",
    className: "Cleric",
    subclassName: "Light Domain (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Cleric:Order Domain (TCoE):none",
    scope: "subclass",
    className: "Cleric",
    subclassName: "Order Domain (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Cleric:Peace Domain (TCoE):none",
    scope: "subclass",
    className: "Cleric",
    subclassName: "Peace Domain (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Cleric:Trickery Domain (2024):none",
    scope: "subclass",
    className: "Cleric",
    subclassName: "Trickery Domain (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Cleric:War Domain (2024):none",
    scope: "subclass",
    className: "Cleric",
    subclassName: "War Domain (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Druid:Circle of Dreams (XGtE):none",
    scope: "subclass",
    className: "Druid",
    subclassName: "Circle of Dreams (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Druid:Circle of Spores (TCoE):none",
    scope: "subclass",
    className: "Druid",
    subclassName: "Circle of Spores (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Druid:Circle of Stars (TCoE):none",
    scope: "subclass",
    className: "Druid",
    subclassName: "Circle of Stars (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Druid:Circle of the Land (2024):none",
    scope: "subclass",
    className: "Druid",
    subclassName: "Circle of the Land (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Druid:Circle of the Moon (2024):none",
    scope: "subclass",
    className: "Druid",
    subclassName: "Circle of the Moon (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Druid:Circle of the Sea (2024):none",
    scope: "subclass",
    className: "Druid",
    subclassName: "Circle of the Sea (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Druid:Circle of the Shepherd (XGtE):none",
    scope: "subclass",
    className: "Druid",
    subclassName: "Circle of the Shepherd (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Druid:Circle of the Stars (2024):none",
    scope: "subclass",
    className: "Druid",
    subclassName: "Circle of the Stars (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Druid:Circle of Wildfire (TCoE):none",
    scope: "subclass",
    className: "Druid",
    subclassName: "Circle of Wildfire (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Fighter:Arcane Archer (XGtE):1",
    scope: "subclass",
    className: "Fighter",
    subclassName: "Arcane Archer (XGtE)",
    resource: "Arcane Shot",
    earliestLevel: 3,
    recovery: "one_expended_use",
    timing: "on_finish_short_rest",
    useLimit: "each_short_rest",
    registryStatus: "AUTHORED_SUBCLASS_SR_RULE_REGISTERED"
  },
  {
    key: "subclass:Fighter:Battle Master (2024):1",
    scope: "subclass",
    className: "Fighter",
    subclassName: "Battle Master (2024)",
    resource: "Superiority Dice",
    earliestLevel: 3,
    recovery: "all_expended_uses",
    timing: "on_finish_short_rest",
    useLimit: "each_short_rest",
    registryStatus: "AUTHORED_SUBCLASS_SR_RULE_REGISTERED"
  },
  {
    key: "subclass:Fighter:Champion (2024):none",
    scope: "subclass",
    className: "Fighter",
    subclassName: "Champion (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Fighter:Echo Knight (EGtW):none",
    scope: "subclass",
    className: "Fighter",
    subclassName: "Echo Knight (EGtW)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Fighter:Eldritch Knight (2024):none",
    scope: "subclass",
    className: "Fighter",
    subclassName: "Eldritch Knight (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Fighter:Psi Warrior (2024):1",
    scope: "subclass",
    className: "Fighter",
    subclassName: "Psi Warrior (2024)",
    resource: "Psionic Energy Dice",
    earliestLevel: 3,
    recovery: "one_expended_use",
    timing: "on_finish_short_rest",
    useLimit: "each_short_rest",
    registryStatus: "AUTHORED_SUBCLASS_SR_RULE_REGISTERED"
  },
  {
    key: "subclass:Fighter:Psi Warrior (TCoE):1",
    scope: "subclass",
    className: "Fighter",
    subclassName: "Psi Warrior (TCoE)",
    resource: "Psionic Energy Dice",
    earliestLevel: 3,
    recovery: "one_expended_use",
    timing: "on_finish_short_rest",
    useLimit: "each_short_rest",
    registryStatus: "AUTHORED_SUBCLASS_SR_RULE_REGISTERED"
  },
  {
    key: "subclass:Fighter:Purple Dragon Knight (SCAG):none",
    scope: "subclass",
    className: "Fighter",
    subclassName: "Purple Dragon Knight (SCAG)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Fighter:Rune Knight (TCoE):none",
    scope: "subclass",
    className: "Fighter",
    subclassName: "Rune Knight (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Fighter:Samurai (XGtE):none",
    scope: "subclass",
    className: "Fighter",
    subclassName: "Samurai (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Gunslinger:Deadeye:none",
    scope: "subclass",
    className: "Gunslinger",
    subclassName: "Deadeye",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Gunslinger:High Roller:none",
    scope: "subclass",
    className: "Gunslinger",
    subclassName: "High Roller",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Gunslinger:Secret Agent:none",
    scope: "subclass",
    className: "Gunslinger",
    subclassName: "Secret Agent",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Gunslinger:Spellslinger:none",
    scope: "subclass",
    className: "Gunslinger",
    subclassName: "Spellslinger",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Gunslinger:Trick Shot:none",
    scope: "subclass",
    className: "Gunslinger",
    subclassName: "Trick Shot",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Gunslinger:White Hat:none",
    scope: "subclass",
    className: "Gunslinger",
    subclassName: "White Hat",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Illrigger:Architect of Ruin:none",
    scope: "subclass",
    className: "Illrigger",
    subclassName: "Architect of Ruin",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "NEEDS_EXTENDED_CLASS_SOURCE"
  },
  {
    key: "subclass:Illrigger:Painkiller:none",
    scope: "subclass",
    className: "Illrigger",
    subclassName: "Painkiller",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "NEEDS_EXTENDED_CLASS_SOURCE"
  },
  {
    key: "subclass:Illrigger:Sanguine Knight:none",
    scope: "subclass",
    className: "Illrigger",
    subclassName: "Sanguine Knight",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "NEEDS_EXTENDED_CLASS_SOURCE"
  },
  {
    key: "subclass:Illrigger:Shadowmaster:none",
    scope: "subclass",
    className: "Illrigger",
    subclassName: "Shadowmaster",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "NEEDS_EXTENDED_CLASS_SOURCE"
  },
  {
    key: "subclass:Monk:Warrior of Mercy (2024):none",
    scope: "subclass",
    className: "Monk",
    subclassName: "Warrior of Mercy (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Monk:Warrior of Shadow (2024):none",
    scope: "subclass",
    className: "Monk",
    subclassName: "Warrior of Shadow (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Monk:Warrior of the Elements (2024):none",
    scope: "subclass",
    className: "Monk",
    subclassName: "Warrior of the Elements (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Monk:Way of the Ascendant Dragon (FToD):none",
    scope: "subclass",
    className: "Monk",
    subclassName: "Way of the Ascendant Dragon (FToD)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Monk:Way of the Astral Self (TCoE):none",
    scope: "subclass",
    className: "Monk",
    subclassName: "Way of the Astral Self (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Monk:Way of the Drunken Master (XGtE):none",
    scope: "subclass",
    className: "Monk",
    subclassName: "Way of the Drunken Master (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Monk:Way of the Kensei (XGtE):none",
    scope: "subclass",
    className: "Monk",
    subclassName: "Way of the Kensei (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Monk:Way of the Long Death (SCAG):none",
    scope: "subclass",
    className: "Monk",
    subclassName: "Way of the Long Death (SCAG)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Monk:Way of the Sun Soul (XGtE):none",
    scope: "subclass",
    className: "Monk",
    subclassName: "Way of the Sun Soul (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Paladin:Oath of Conquest (XGtE):none",
    scope: "subclass",
    className: "Paladin",
    subclassName: "Oath of Conquest (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Paladin:Oath of Devotion (2024):none",
    scope: "subclass",
    className: "Paladin",
    subclassName: "Oath of Devotion (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Paladin:Oath of Glory (2024):none",
    scope: "subclass",
    className: "Paladin",
    subclassName: "Oath of Glory (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Paladin:Oath of Glory (TCoE):none",
    scope: "subclass",
    className: "Paladin",
    subclassName: "Oath of Glory (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Paladin:Oath of Redemption (XGtE):none",
    scope: "subclass",
    className: "Paladin",
    subclassName: "Oath of Redemption (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Paladin:Oath of the Ancients (2024):none",
    scope: "subclass",
    className: "Paladin",
    subclassName: "Oath of the Ancients (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Paladin:Oath of the Crown (SCAG):none",
    scope: "subclass",
    className: "Paladin",
    subclassName: "Oath of the Crown (SCAG)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Paladin:Oath of the Watchers (TCoE):none",
    scope: "subclass",
    className: "Paladin",
    subclassName: "Oath of the Watchers (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Paladin:Oath of Vengeance (2024):none",
    scope: "subclass",
    className: "Paladin",
    subclassName: "Oath of Vengeance (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Ranger:Beast Master (2024):none",
    scope: "subclass",
    className: "Ranger",
    subclassName: "Beast Master (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Ranger:Drakewarden (FToD):none",
    scope: "subclass",
    className: "Ranger",
    subclassName: "Drakewarden (FToD)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Ranger:Fey Wanderer (2024):none",
    scope: "subclass",
    className: "Ranger",
    subclassName: "Fey Wanderer (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Ranger:Fey Wanderer (TCoE):none",
    scope: "subclass",
    className: "Ranger",
    subclassName: "Fey Wanderer (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Ranger:Gloom Stalker (2024):none",
    scope: "subclass",
    className: "Ranger",
    subclassName: "Gloom Stalker (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Ranger:Gloom Stalker (XGtE):none",
    scope: "subclass",
    className: "Ranger",
    subclassName: "Gloom Stalker (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Ranger:Horizon Walker (XGtE):none",
    scope: "subclass",
    className: "Ranger",
    subclassName: "Horizon Walker (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Ranger:Hunter (2024):none",
    scope: "subclass",
    className: "Ranger",
    subclassName: "Hunter (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Ranger:Monster Slayer (XGtE):none",
    scope: "subclass",
    className: "Ranger",
    subclassName: "Monster Slayer (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Ranger:Swarmkeeper (TCoE):none",
    scope: "subclass",
    className: "Ranger",
    subclassName: "Swarmkeeper (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Rogue:Arcane Trickster (2024):none",
    scope: "subclass",
    className: "Rogue",
    subclassName: "Arcane Trickster (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Rogue:Assassin (2024):none",
    scope: "subclass",
    className: "Rogue",
    subclassName: "Assassin (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Rogue:Mastermind (XGtE):none",
    scope: "subclass",
    className: "Rogue",
    subclassName: "Mastermind (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Rogue:Phantom (TCoE):none",
    scope: "subclass",
    className: "Rogue",
    subclassName: "Phantom (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Rogue:Scout (XGtE):none",
    scope: "subclass",
    className: "Rogue",
    subclassName: "Scout (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Rogue:Soulknife (2024):1",
    scope: "subclass",
    className: "Rogue",
    subclassName: "Soulknife (2024)",
    resource: "Psionic Energy Dice",
    earliestLevel: 3,
    recovery: "one_expended_use",
    timing: "on_finish_short_rest",
    useLimit: "each_short_rest",
    registryStatus: "AUTHORED_SUBCLASS_SR_RULE_REGISTERED"
  },
  {
    key: "subclass:Rogue:Soulknife (TCoE):1",
    scope: "subclass",
    className: "Rogue",
    subclassName: "Soulknife (TCoE)",
    resource: "Psionic Energy Dice",
    earliestLevel: 3,
    recovery: "one_expended_use",
    timing: "on_finish_short_rest",
    useLimit: "each_short_rest",
    registryStatus: "AUTHORED_SUBCLASS_SR_RULE_REGISTERED"
  },
  {
    key: "subclass:Rogue:Swashbuckler (XGtE):none",
    scope: "subclass",
    className: "Rogue",
    subclassName: "Swashbuckler (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Rogue:Thief (2024):none",
    scope: "subclass",
    className: "Rogue",
    subclassName: "Thief (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Sorcerer:Aberrant Mind (TCoE):none",
    scope: "subclass",
    className: "Sorcerer",
    subclassName: "Aberrant Mind (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Sorcerer:Aberrant Sorcery (2024):none",
    scope: "subclass",
    className: "Sorcerer",
    subclassName: "Aberrant Sorcery (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Sorcerer:Clockwork Sorcery (2024):none",
    scope: "subclass",
    className: "Sorcerer",
    subclassName: "Clockwork Sorcery (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Sorcerer:Clockwork Soul (TCoE):none",
    scope: "subclass",
    className: "Sorcerer",
    subclassName: "Clockwork Soul (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Sorcerer:Divine Soul (XGtE):none",
    scope: "subclass",
    className: "Sorcerer",
    subclassName: "Divine Soul (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Sorcerer:Draconic Sorcery (2024):none",
    scope: "subclass",
    className: "Sorcerer",
    subclassName: "Draconic Sorcery (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Sorcerer:Lunar Sorcery (DSotDQ):none",
    scope: "subclass",
    className: "Sorcerer",
    subclassName: "Lunar Sorcery (DSotDQ)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Sorcerer:Shadow Magic (XGtE):none",
    scope: "subclass",
    className: "Sorcerer",
    subclassName: "Shadow Magic (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Sorcerer:Storm Sorcery (XGtE):none",
    scope: "subclass",
    className: "Sorcerer",
    subclassName: "Storm Sorcery (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Sorcerer:Wild Magic Sorcery (2024):none",
    scope: "subclass",
    className: "Sorcerer",
    subclassName: "Wild Magic Sorcery (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Warlock:Archfey Patron (2024):none",
    scope: "subclass",
    className: "Warlock",
    subclassName: "Archfey Patron (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Warlock:Fiend Patron (2024):none",
    scope: "subclass",
    className: "Warlock",
    subclassName: "Fiend Patron (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Warlock:Great Old One Patron (2024):none",
    scope: "subclass",
    className: "Warlock",
    subclassName: "Great Old One Patron (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Warlock:The Fathomless (TCoE):none",
    scope: "subclass",
    className: "Warlock",
    subclassName: "The Fathomless (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Warlock:The Genie (TCoE):none",
    scope: "subclass",
    className: "Warlock",
    subclassName: "The Genie (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Warlock:The Hexblade (XGtE):none",
    scope: "subclass",
    className: "Warlock",
    subclassName: "The Hexblade (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Warlock:The Undead (VRGtR):none",
    scope: "subclass",
    className: "Warlock",
    subclassName: "The Undead (VRGtR)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Warlock:The Undying (SCAG):none",
    scope: "subclass",
    className: "Warlock",
    subclassName: "The Undying (SCAG)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Wizard:Abjurer (2024):none",
    scope: "subclass",
    className: "Wizard",
    subclassName: "Abjurer (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Wizard:Bladesinging (TCoE):none",
    scope: "subclass",
    className: "Wizard",
    subclassName: "Bladesinging (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Wizard:Chronurgy Magic (EGtW):none",
    scope: "subclass",
    className: "Wizard",
    subclassName: "Chronurgy Magic (EGtW)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Wizard:Diviner (2024):none",
    scope: "subclass",
    className: "Wizard",
    subclassName: "Diviner (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Wizard:Evoker (2024):none",
    scope: "subclass",
    className: "Wizard",
    subclassName: "Evoker (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Wizard:Graviturgy Magic (EGtW):none",
    scope: "subclass",
    className: "Wizard",
    subclassName: "Graviturgy Magic (EGtW)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Wizard:Illusionist (2024):none",
    scope: "subclass",
    className: "Wizard",
    subclassName: "Illusionist (2024)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Wizard:Order of Scribes (TCoE):none",
    scope: "subclass",
    className: "Wizard",
    subclassName: "Order of Scribes (TCoE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  },
  {
    key: "subclass:Wizard:War Magic (XGtE):none",
    scope: "subclass",
    className: "Wizard",
    subclassName: "War Magic (XGtE)",
    resource: "No separate Short-Rest resource; inherit all applicable class rules.",
    earliestLevel: 0,
    recovery: null,
    timing: null,
    useLimit: null,
    registryStatus: "INHERITS_CLASS_BASELINE_NO_SEPARATE_SR_RESOURCE_REGISTERED"
  }
];

/*
 * ⚠ ONE FUNCTION, DELIBERATELY. check:wiring fails a NEW ORPHAN EXPORT, and a convenience lookup
 * nobody calls is exactly that. A classShortRestRules and a knownShortRestClass were written here
 * and removed again for want of a caller; add them back WITH the code that needs them, not before.
 */
/**
 * The rules that actually apply to one character: their class rules plus their subclass's own,
 * filtered to the levels they have reached.
 *
 * ⚠ SUBCLASS IS ADDITIVE. The sheet's own treatment column says a subclass "may add only its own
 * named asset recovery" — it never replaces what the class already grants, so both lists are
 * returned rather than the subclass shadowing the class.
 */
export function shortRestRulesFor(
  className: string,
  subclassName: string | null | undefined,
  level: number,
): ShortRestRule[] {
  const cls = className.trim().toLowerCase();
  const sub = (subclassName ?? "").trim().toLowerCase();
  return SHORT_REST_RULES.filter(r => {
    if (r.className.toLowerCase() !== cls) return false;
    if (r.scope === "subclass" && (!sub || (r.subclassName ?? "").toLowerCase() !== sub)) return false;
    if (r.earliestLevel !== null && level < r.earliestLevel) return false;
    return true;
  });
}

