/**
 * SRD 5.2.1 AUDIT CHASSIS MAP — generated. Do not hand-edit.
 *
 * ⚠ GENERATED by `scripts/import-srd-audit.mjs` from Christopher's
 * `SRD_5.2.1_creature_pricing_mechanics_audit.md`, which walked all 330 stat blocks on
 * printed pages 258-364. RULE 1: that document is the authority. Where it and our PDF parse
 * disagree, it wins — it read the printed pages; the parser read a text layer that drops digits.
 *
 * ⚠ HEADER LINE ONLY. No traits, no actions, no damage. This COMPLETES a parsed creature and
 * PROVES an absent one; it can never stand in for one. A creature with AC and HP and no actions
 * prices at zero DPR, which is a wrong answer wearing the shape of an answer.
 *
 * 330 chassis rows · 28 distinct new/extended primitives · 5 CR 26-30 estimator rows.
 */

/** One SRD stat block's header line, as the audit published it. */
export type SrdAuditChassis = {
  /** Printed page in the SRD, so a disagreement can be checked against the source. */
  page: number;
  name: string;
  /** As printed — "1/8", "0", "21". Kept as text because CR is not a number in the general case. */
  cr: string;
  size: string;
  creatureType: string;
  ac: number;
  hp: number;
  /** M01-M28: the pricing primitives this block needs beyond the workbook's current set. */
  primitives: string[];
};

/** One row of the CR 26-30 extension the audit specifies as M28. */
export type SrdAuditCrRow = {
  cr: number;
  proficiencyBonus: number;
  expectedAc: number;
  hpLow: number;
  hpHigh: number;
  expectedAttackBonus: number;
  dprLow: number;
  dprHigh: number;
  expectedSaveDc: number;
};

export const SRD_AUDIT_CHASSIS: SrdAuditChassis[] = [
 {
  "page": 258,
  "name": "Aboleth",
  "cr": "10",
  "size": "Large",
  "creatureType": "Aberration",
  "ac": 17,
  "hp": 150,
  "primitives": [
   "M02"
  ]
 },
 {
  "page": 264,
  "name": "Adult Black Dragon",
  "cr": "14",
  "size": "Huge",
  "creatureType": "Dragon (Chromatic)",
  "ac": 19,
  "hp": 195,
  "primitives": [
   "M01",
   "M02",
   "M03",
   "M20"
  ]
 },
 {
  "page": 266,
  "name": "Adult Blue Dragon",
  "cr": "16",
  "size": "Huge",
  "creatureType": "Dragon (Chromatic)",
  "ac": 19,
  "hp": 212,
  "primitives": [
   "M01",
   "M02",
   "M20"
  ]
 },
 {
  "page": 268,
  "name": "Adult Brass Dragon",
  "cr": "13",
  "size": "Huge",
  "creatureType": "Dragon (Metallic)",
  "ac": 18,
  "hp": 172,
  "primitives": [
   "M01",
   "M02",
   "M03",
   "M12",
   "M20"
  ]
 },
 {
  "page": 270,
  "name": "Adult Bronze Dragon",
  "cr": "15",
  "size": "Huge",
  "creatureType": "Dragon (Metallic)",
  "ac": 18,
  "hp": 212,
  "primitives": [
   "M01",
   "M02",
   "M03",
   "M20"
  ]
 },
 {
  "page": 276,
  "name": "Adult Copper Dragon",
  "cr": "14",
  "size": "Huge",
  "creatureType": "Dragon (Metallic)",
  "ac": 18,
  "hp": 184,
  "primitives": [
   "M01",
   "M02",
   "M03",
   "M13",
   "M15",
   "M20"
  ]
 },
 {
  "page": 291,
  "name": "Adult Gold Dragon",
  "cr": "17",
  "size": "Huge",
  "creatureType": "Dragon (Metallic)",
  "ac": 19,
  "hp": 243,
  "primitives": [
   "M01",
   "M02",
   "M03",
   "M15",
   "M20",
   "M23"
  ]
 },
 {
  "page": 294,
  "name": "Adult Green Dragon",
  "cr": "15",
  "size": "Huge",
  "creatureType": "Dragon (Chromatic)",
  "ac": 19,
  "hp": 207,
  "primitives": [
   "M01",
   "M02",
   "M20"
  ]
 },
 {
  "page": 318,
  "name": "Adult Red Dragon",
  "cr": "17",
  "size": "Huge",
  "creatureType": "Dragon (Chromatic)",
  "ac": 19,
  "hp": 256,
  "primitives": [
   "M01",
   "M02",
   "M20"
  ]
 },
 {
  "page": 324,
  "name": "Adult Silver Dragon",
  "cr": "16",
  "size": "Huge",
  "creatureType": "Dragon (Metallic)",
  "ac": 19,
  "hp": 216,
  "primitives": [
   "M01",
   "M02",
   "M03",
   "M12",
   "M20"
  ]
 },
 {
  "page": 340,
  "name": "Adult White Dragon",
  "cr": "13",
  "size": "Huge",
  "creatureType": "Dragon (Chromatic)",
  "ac": 18,
  "hp": 200,
  "primitives": [
   "M01",
   "M02",
   "M20"
  ]
 },
 {
  "page": 258,
  "name": "Air Elemental",
  "cr": "5",
  "size": "Large",
  "creatureType": "Elemental",
  "ac": 15,
  "hp": 90,
  "primitives": [
   "M02"
  ]
 },
 {
  "page": 344,
  "name": "Allosaurus",
  "cr": "2",
  "size": "Large",
  "creatureType": "Beast (Dinosaur)",
  "ac": 13,
  "hp": 51,
  "primitives": []
 },
 {
  "page": 265,
  "name": "Ancient Black Dragon",
  "cr": "21",
  "size": "Gargantuan",
  "creatureType": "Dragon (Chromatic)",
  "ac": 22,
  "hp": 367,
  "primitives": [
   "M01",
   "M02",
   "M03",
   "M20"
  ]
 },
 {
  "page": 267,
  "name": "Ancient Blue Dragon",
  "cr": "23",
  "size": "Gargantuan",
  "creatureType": "Dragon (Chromatic)",
  "ac": 22,
  "hp": 481,
  "primitives": [
   "M01",
   "M02",
   "M20"
  ]
 },
 {
  "page": 269,
  "name": "Ancient Brass Dragon",
  "cr": "20",
  "size": "Gargantuan",
  "creatureType": "Dragon (Metallic)",
  "ac": 20,
  "hp": 332,
  "primitives": [
   "M01",
   "M02",
   "M03",
   "M12",
   "M20"
  ]
 },
 {
  "page": 271,
  "name": "Ancient Bronze Dragon",
  "cr": "22",
  "size": "Gargantuan",
  "creatureType": "Dragon (Metallic)",
  "ac": 22,
  "hp": 444,
  "primitives": [
   "M01",
   "M02",
   "M03",
   "M20"
  ]
 },
 {
  "page": 277,
  "name": "Ancient Copper Dragon",
  "cr": "21",
  "size": "Gargantuan",
  "creatureType": "Dragon (Metallic)",
  "ac": 21,
  "hp": 367,
  "primitives": [
   "M01",
   "M02",
   "M03",
   "M13",
   "M15",
   "M20"
  ]
 },
 {
  "page": 292,
  "name": "Ancient Gold Dragon",
  "cr": "24",
  "size": "Gargantuan",
  "creatureType": "Dragon (Metallic)",
  "ac": 22,
  "hp": 546,
  "primitives": [
   "M01",
   "M02",
   "M03",
   "M15",
   "M20",
   "M23"
  ]
 },
 {
  "page": 294,
  "name": "Ancient Green Dragon",
  "cr": "22",
  "size": "Gargantuan",
  "creatureType": "Dragon (Chromatic)",
  "ac": 21,
  "hp": 402,
  "primitives": [
   "M01",
   "M02",
   "M20"
  ]
 },
 {
  "page": 319,
  "name": "Ancient Red Dragon",
  "cr": "24",
  "size": "Gargantuan",
  "creatureType": "Dragon (Chromatic)",
  "ac": 22,
  "hp": 507,
  "primitives": [
   "M01",
   "M02",
   "M20"
  ]
 },
 {
  "page": 325,
  "name": "Ancient Silver Dragon",
  "cr": "23",
  "size": "Gargantuan",
  "creatureType": "Dragon (Metallic)",
  "ac": 22,
  "hp": 468,
  "primitives": [
   "M01",
   "M02",
   "M03",
   "M12",
   "M20"
  ]
 },
 {
  "page": 341,
  "name": "Ancient White Dragon",
  "cr": "20",
  "size": "Gargantuan",
  "creatureType": "Dragon (Chromatic)",
  "ac": 20,
  "hp": 333,
  "primitives": [
   "M01",
   "M02",
   "M20"
  ]
 },
 {
  "page": 259,
  "name": "Animated Armor",
  "cr": "1",
  "size": "Medium",
  "creatureType": "Construct",
  "ac": 18,
  "hp": 33,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 259,
  "name": "Animated Flying Sword",
  "cr": "1/4",
  "size": "Small",
  "creatureType": "Construct",
  "ac": 17,
  "hp": 14,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 259,
  "name": "Animated Rug of Smothering",
  "cr": "2",
  "size": "Large",
  "creatureType": "Construct",
  "ac": 12,
  "hp": 27,
  "primitives": [
   "M20",
   "M26"
  ]
 },
 {
  "page": 259,
  "name": "Ankheg",
  "cr": "2",
  "size": "Large",
  "creatureType": "Monstrosity",
  "ac": 14,
  "hp": 45,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 344,
  "name": "Ankylosaurus",
  "cr": "3",
  "size": "Huge",
  "creatureType": "Beast (Dinosaur)",
  "ac": 15,
  "hp": 68,
  "primitives": []
 },
 {
  "page": 344,
  "name": "Ape",
  "cr": "1/2",
  "size": "Medium",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 19,
  "primitives": [
   "M02"
  ]
 },
 {
  "page": 344,
  "name": "Archelon",
  "cr": "4",
  "size": "Huge",
  "creatureType": "Beast (Dinosaur)",
  "ac": 17,
  "hp": 90,
  "primitives": []
 },
 {
  "page": 305,
  "name": "Archmage",
  "cr": "12",
  "size": "Medium or Small",
  "creatureType": "Humanoid (Wizard)",
  "ac": 17,
  "hp": 170,
  "primitives": [
   "M01",
   "M02"
  ]
 },
 {
  "page": 260,
  "name": "Assassin",
  "cr": "8",
  "size": "Medium or Small",
  "creatureType": "Humanoid",
  "ac": 16,
  "hp": 97,
  "primitives": [
   "M04"
  ]
 },
 {
  "page": 260,
  "name": "Awakened Shrub",
  "cr": "0",
  "size": "Small",
  "creatureType": "Plant",
  "ac": 9,
  "hp": 10,
  "primitives": []
 },
 {
  "page": 260,
  "name": "Awakened Tree",
  "cr": "2",
  "size": "Huge",
  "creatureType": "Plant",
  "ac": 13,
  "hp": 59,
  "primitives": []
 },
 {
  "page": 260,
  "name": "Axe Beak",
  "cr": "1/4",
  "size": "Large",
  "creatureType": "Monstrosity",
  "ac": 11,
  "hp": 19,
  "primitives": []
 },
 {
  "page": 261,
  "name": "Azer Sentinel",
  "cr": "2",
  "size": "Medium",
  "creatureType": "Elemental",
  "ac": 17,
  "hp": 39,
  "primitives": []
 },
 {
  "page": 345,
  "name": "Baboon",
  "cr": "0",
  "size": "Small",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 3,
  "primitives": []
 },
 {
  "page": 345,
  "name": "Badger",
  "cr": "0",
  "size": "Tiny",
  "creatureType": "Beast",
  "ac": 11,
  "hp": 5,
  "primitives": []
 },
 {
  "page": 261,
  "name": "Balor",
  "cr": "19",
  "size": "Huge",
  "creatureType": "Fiend (Demon)",
  "ac": 19,
  "hp": 287,
  "primitives": [
   "M02",
   "M20"
  ]
 },
 {
  "page": 261,
  "name": "Bandit",
  "cr": "1/8",
  "size": "Medium or Small",
  "creatureType": "Humanoid",
  "ac": 12,
  "hp": 11,
  "primitives": []
 },
 {
  "page": 261,
  "name": "Bandit Captain",
  "cr": "2",
  "size": "Medium or Small",
  "creatureType": "Humanoid",
  "ac": 15,
  "hp": 52,
  "primitives": []
 },
 {
  "page": 262,
  "name": "Barbed Devil",
  "cr": "5",
  "size": "Medium",
  "creatureType": "Fiend (Devil)",
  "ac": 15,
  "hp": 110,
  "primitives": []
 },
 {
  "page": 262,
  "name": "Basilisk",
  "cr": "3",
  "size": "Medium",
  "creatureType": "Monstrosity",
  "ac": 15,
  "hp": 52,
  "primitives": [
   "M12"
  ]
 },
 {
  "page": 345,
  "name": "Bat",
  "cr": "0",
  "size": "Tiny",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 1,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 262,
  "name": "Bearded Devil",
  "cr": "3",
  "size": "Medium",
  "creatureType": "Fiend (Devil)",
  "ac": 13,
  "hp": 58,
  "primitives": []
 },
 {
  "page": 263,
  "name": "Behir",
  "cr": "11",
  "size": "Huge",
  "creatureType": "Monstrosity",
  "ac": 17,
  "hp": 168,
  "primitives": [
   "M02"
  ]
 },
 {
  "page": 263,
  "name": "Berserker",
  "cr": "2",
  "size": "Medium or Small",
  "creatureType": "Humanoid",
  "ac": 13,
  "hp": 67,
  "primitives": []
 },
 {
  "page": 345,
  "name": "Black Bear",
  "cr": "1/2",
  "size": "Medium",
  "creatureType": "Beast",
  "ac": 11,
  "hp": 19,
  "primitives": []
 },
 {
  "page": 263,
  "name": "Black Dragon Wyrmling",
  "cr": "2",
  "size": "Medium",
  "creatureType": "Dragon (Chromatic)",
  "ac": 17,
  "hp": 33,
  "primitives": [
   "M02",
   "M20"
  ]
 },
 {
  "page": 265,
  "name": "Black Pudding",
  "cr": "4",
  "size": "Large",
  "creatureType": "Ooze",
  "ac": 7,
  "hp": 68,
  "primitives": [
   "M16",
   "M20"
  ]
 },
 {
  "page": 266,
  "name": "Blink Dog",
  "cr": "1/4",
  "size": "Medium",
  "creatureType": "Fey",
  "ac": 13,
  "hp": 22,
  "primitives": []
 },
 {
  "page": 345,
  "name": "Blood Hawk",
  "cr": "1/8",
  "size": "Small",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 7,
  "primitives": []
 },
 {
  "page": 266,
  "name": "Blue Dragon Wyrmling",
  "cr": "3",
  "size": "Medium",
  "creatureType": "Dragon (Chromatic)",
  "ac": 17,
  "hp": 65,
  "primitives": [
   "M02",
   "M20"
  ]
 },
 {
  "page": 346,
  "name": "Boar",
  "cr": "1/4",
  "size": "Medium",
  "creatureType": "Beast",
  "ac": 11,
  "hp": 13,
  "primitives": []
 },
 {
  "page": 267,
  "name": "Bone Devil",
  "cr": "9",
  "size": "Large",
  "creatureType": "Fiend (Devil)",
  "ac": 16,
  "hp": 161,
  "primitives": []
 },
 {
  "page": 268,
  "name": "Brass Dragon Wyrmling",
  "cr": "1",
  "size": "Medium",
  "creatureType": "Dragon (Metallic)",
  "ac": 15,
  "hp": 22,
  "primitives": [
   "M12",
   "M20"
  ]
 },
 {
  "page": 269,
  "name": "Bronze Dragon Wyrmling",
  "cr": "2",
  "size": "Medium",
  "creatureType": "Dragon (Metallic)",
  "ac": 15,
  "hp": 39,
  "primitives": [
   "M02",
   "M20"
  ]
 },
 {
  "page": 346,
  "name": "Brown Bear",
  "cr": "1",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 11,
  "hp": 22,
  "primitives": []
 },
 {
  "page": 271,
  "name": "Bugbear Stalker",
  "cr": "3",
  "size": "Medium",
  "creatureType": "Fey (Goblinoid)",
  "ac": 15,
  "hp": 65,
  "primitives": []
 },
 {
  "page": 272,
  "name": "Bugbear Warrior",
  "cr": "1",
  "size": "Medium",
  "creatureType": "Fey (Goblinoid)",
  "ac": 14,
  "hp": 33,
  "primitives": []
 },
 {
  "page": 272,
  "name": "Bulette",
  "cr": "5",
  "size": "Large",
  "creatureType": "Monstrosity",
  "ac": 17,
  "hp": 94,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 346,
  "name": "Camel",
  "cr": "1/8",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 10,
  "hp": 17,
  "primitives": []
 },
 {
  "page": 346,
  "name": "Cat",
  "cr": "0",
  "size": "Tiny",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 2,
  "primitives": []
 },
 {
  "page": 272,
  "name": "Centaur Trooper",
  "cr": "2",
  "size": "Large",
  "creatureType": "Fey",
  "ac": 16,
  "hp": 45,
  "primitives": [
   "M02"
  ]
 },
 {
  "page": 272,
  "name": "Chain Devil",
  "cr": "8",
  "size": "Medium",
  "creatureType": "Fiend (Devil)",
  "ac": 15,
  "hp": 85,
  "primitives": [
   "M21"
  ]
 },
 {
  "page": 273,
  "name": "Chimera",
  "cr": "6",
  "size": "Large",
  "creatureType": "Monstrosity",
  "ac": 14,
  "hp": 114,
  "primitives": [
   "M02"
  ]
 },
 {
  "page": 273,
  "name": "Chuul",
  "cr": "4",
  "size": "Large",
  "creatureType": "Aberration",
  "ac": 16,
  "hp": 76,
  "primitives": []
 },
 {
  "page": 274,
  "name": "Clay Golem",
  "cr": "9",
  "size": "Large",
  "creatureType": "Construct",
  "ac": 14,
  "hp": 123,
  "primitives": [
   "M02",
   "M07",
   "M09",
   "M14"
  ]
 },
 {
  "page": 274,
  "name": "Cloaker",
  "cr": "8",
  "size": "Large",
  "creatureType": "Aberration",
  "ac": 14,
  "hp": 91,
  "primitives": [
   "M01",
   "M02",
   "M21"
  ]
 },
 {
  "page": 275,
  "name": "Cloud Giant",
  "cr": "9",
  "size": "Huge",
  "creatureType": "Giant",
  "ac": 14,
  "hp": 200,
  "primitives": [
   "M01",
   "M02"
  ]
 },
 {
  "page": 275,
  "name": "Cockatrice",
  "cr": "1/2",
  "size": "Small",
  "creatureType": "Monstrosity",
  "ac": 11,
  "hp": 22,
  "primitives": [
   "M12"
  ]
 },
 {
  "page": 275,
  "name": "Commoner",
  "cr": "0",
  "size": "Medium or Small",
  "creatureType": "Humanoid",
  "ac": 10,
  "hp": 4,
  "primitives": []
 },
 {
  "page": 346,
  "name": "Constrictor Snake",
  "cr": "1/4",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 13,
  "hp": 13,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 275,
  "name": "Copper Dragon Wyrmling",
  "cr": "1",
  "size": "Medium",
  "creatureType": "Dragon (Metallic)",
  "ac": 16,
  "hp": 22,
  "primitives": [
   "M13",
   "M20"
  ]
 },
 {
  "page": 277,
  "name": "Couatl",
  "cr": "4",
  "size": "Medium",
  "creatureType": "Celestial",
  "ac": 19,
  "hp": 60,
  "primitives": [
   "M01",
   "M03",
   "M20"
  ]
 },
 {
  "page": 347,
  "name": "Crab",
  "cr": "0",
  "size": "Tiny",
  "creatureType": "Beast",
  "ac": 11,
  "hp": 3,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 347,
  "name": "Crocodile",
  "cr": "1/2",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 13,
  "primitives": []
 },
 {
  "page": 278,
  "name": "Cultist",
  "cr": "1/8",
  "size": "Medium or Small",
  "creatureType": "Humanoid",
  "ac": 12,
  "hp": 9,
  "primitives": []
 },
 {
  "page": 278,
  "name": "Cultist Fanatic",
  "cr": "2",
  "size": "Medium or Small",
  "creatureType": "Humanoid",
  "ac": 13,
  "hp": 44,
  "primitives": [
   "M01"
  ]
 },
 {
  "page": 278,
  "name": "Darkmantle",
  "cr": "1/2",
  "size": "Small",
  "creatureType": "Aberration",
  "ac": 11,
  "hp": 22,
  "primitives": [
   "M03",
   "M20",
   "M26"
  ]
 },
 {
  "page": 279,
  "name": "Death Dog",
  "cr": "1",
  "size": "Medium",
  "creatureType": "Monstrosity",
  "ac": 12,
  "hp": 39,
  "primitives": [
   "M09",
   "M12"
  ]
 },
 {
  "page": 347,
  "name": "Deer",
  "cr": "0",
  "size": "Medium",
  "creatureType": "Beast",
  "ac": 13,
  "hp": 4,
  "primitives": []
 },
 {
  "page": 279,
  "name": "Deva",
  "cr": "10",
  "size": "Medium",
  "creatureType": "Celestial (Angel)",
  "ac": 17,
  "hp": 229,
  "primitives": [
   "M01",
   "M02",
   "M03"
  ]
 },
 {
  "page": 347,
  "name": "Dire Wolf",
  "cr": "1",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 14,
  "hp": 22,
  "primitives": []
 },
 {
  "page": 280,
  "name": "Djinni",
  "cr": "11",
  "size": "Large",
  "creatureType": "Elemental (Genie)",
  "ac": 17,
  "hp": 218,
  "primitives": [
   "M01",
   "M02",
   "M03",
   "M22"
  ]
 },
 {
  "page": 280,
  "name": "Doppelganger",
  "cr": "3",
  "size": "Medium",
  "creatureType": "Monstrosity",
  "ac": 14,
  "hp": 52,
  "primitives": [
   "M01",
   "M02"
  ]
 },
 {
  "page": 347,
  "name": "Draft Horse",
  "cr": "1/4",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 10,
  "hp": 15,
  "primitives": []
 },
 {
  "page": 281,
  "name": "Dragon Turtle",
  "cr": "17",
  "size": "Gargantuan",
  "creatureType": "Dragon",
  "ac": 20,
  "hp": 356,
  "primitives": [
   "M02"
  ]
 },
 {
  "page": 281,
  "name": "Dretch",
  "cr": "1/4",
  "size": "Small",
  "creatureType": "Fiend (Demon)",
  "ac": 11,
  "hp": 18,
  "primitives": [
   "M13"
  ]
 },
 {
  "page": 281,
  "name": "Drider",
  "cr": "6",
  "size": "Large",
  "creatureType": "Monstrosity",
  "ac": 19,
  "hp": 123,
  "primitives": [
   "M01",
   "M02",
   "M20"
  ]
 },
 {
  "page": 282,
  "name": "Druid",
  "cr": "2",
  "size": "Medium or Small",
  "creatureType": "Humanoid (Druid)",
  "ac": 13,
  "hp": 44,
  "primitives": [
   "M01",
   "M02"
  ]
 },
 {
  "page": 282,
  "name": "Dryad",
  "cr": "1",
  "size": "Medium",
  "creatureType": "Fey",
  "ac": 16,
  "hp": 22,
  "primitives": [
   "M01",
   "M02"
  ]
 },
 {
  "page": 307,
  "name": "Dust Mephit",
  "cr": "1/2",
  "size": "Small",
  "creatureType": "Elemental",
  "ac": 12,
  "hp": 17,
  "primitives": [
   "M01"
  ]
 },
 {
  "page": 348,
  "name": "Eagle",
  "cr": "0",
  "size": "Small",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 4,
  "primitives": []
 },
 {
  "page": 282,
  "name": "Earth Elemental",
  "cr": "5",
  "size": "Large",
  "creatureType": "Elemental",
  "ac": 17,
  "hp": 147,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 283,
  "name": "Efreeti",
  "cr": "11",
  "size": "Large",
  "creatureType": "Elemental (Genie)",
  "ac": 17,
  "hp": 212,
  "primitives": [
   "M01",
   "M02"
  ]
 },
 {
  "page": 348,
  "name": "Elephant",
  "cr": "4",
  "size": "Huge",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 76,
  "primitives": []
 },
 {
  "page": 348,
  "name": "Elk",
  "cr": "1/4",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 10,
  "hp": 11,
  "primitives": []
 },
 {
  "page": 283,
  "name": "Erinyes",
  "cr": "12",
  "size": "Medium",
  "creatureType": "Fiend (Devil)",
  "ac": 18,
  "hp": 178,
  "primitives": [
   "M17",
   "M20"
  ]
 },
 {
  "page": 284,
  "name": "Ettercap",
  "cr": "2",
  "size": "Medium",
  "creatureType": "Monstrosity",
  "ac": 13,
  "hp": 44,
  "primitives": [
   "M02",
   "M17",
   "M20"
  ]
 },
 {
  "page": 284,
  "name": "Ettin",
  "cr": "4",
  "size": "Large",
  "creatureType": "Giant",
  "ac": 12,
  "hp": 85,
  "primitives": []
 },
 {
  "page": 284,
  "name": "Fire Elemental",
  "cr": "5",
  "size": "Large",
  "creatureType": "Elemental",
  "ac": 13,
  "hp": 93,
  "primitives": []
 },
 {
  "page": 285,
  "name": "Fire Giant",
  "cr": "9",
  "size": "Huge",
  "creatureType": "Giant",
  "ac": 18,
  "hp": 162,
  "primitives": []
 },
 {
  "page": 285,
  "name": "Flesh Golem",
  "cr": "5",
  "size": "Medium",
  "creatureType": "Construct",
  "ac": 9,
  "hp": 127,
  "primitives": [
   "M07",
   "M14"
  ]
 },
 {
  "page": 348,
  "name": "Flying Snake",
  "cr": "1/8",
  "size": "Tiny",
  "creatureType": "Monstrosity",
  "ac": 14,
  "hp": 5,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 348,
  "name": "Frog",
  "cr": "0",
  "size": "Tiny",
  "creatureType": "Beast",
  "ac": 11,
  "hp": 1,
  "primitives": []
 },
 {
  "page": 285,
  "name": "Frost Giant",
  "cr": "8",
  "size": "Huge",
  "creatureType": "Giant",
  "ac": 15,
  "hp": 149,
  "primitives": [
   "M02"
  ]
 },
 {
  "page": 286,
  "name": "Gargoyle",
  "cr": "2",
  "size": "Medium",
  "creatureType": "Elemental",
  "ac": 15,
  "hp": 67,
  "primitives": []
 },
 {
  "page": 286,
  "name": "Gelatinous Cube",
  "cr": "2",
  "size": "Large",
  "creatureType": "Ooze",
  "ac": 6,
  "hp": 63,
  "primitives": [
   "M13",
   "M20",
   "M24",
   "M26"
  ]
 },
 {
  "page": 287,
  "name": "Ghast",
  "cr": "2",
  "size": "Medium",
  "creatureType": "Undead",
  "ac": 13,
  "hp": 36,
  "primitives": [
   "M21"
  ]
 },
 {
  "page": 287,
  "name": "Ghost",
  "cr": "4",
  "size": "Medium",
  "creatureType": "Undead",
  "ac": 11,
  "hp": 45,
  "primitives": [
   "M01",
   "M02",
   "M11",
   "M18",
   "M19",
   "M20",
   "M21"
  ]
 },
 {
  "page": 288,
  "name": "Ghoul",
  "cr": "1",
  "size": "Medium",
  "creatureType": "Undead",
  "ac": 12,
  "hp": 22,
  "primitives": []
 },
 {
  "page": 349,
  "name": "Giant Ape",
  "cr": "7",
  "size": "Huge",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 168,
  "primitives": [
   "M02"
  ]
 },
 {
  "page": 349,
  "name": "Giant Badger",
  "cr": "1/4",
  "size": "Medium",
  "creatureType": "Beast",
  "ac": 13,
  "hp": 15,
  "primitives": []
 },
 {
  "page": 349,
  "name": "Giant Bat",
  "cr": "1/4",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 13,
  "hp": 22,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 349,
  "name": "Giant Boar",
  "cr": "2",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 13,
  "hp": 42,
  "primitives": []
 },
 {
  "page": 349,
  "name": "Giant Centipede",
  "cr": "1/4",
  "size": "Small",
  "creatureType": "Beast",
  "ac": 14,
  "hp": 9,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 350,
  "name": "Giant Constrictor Snake",
  "cr": "2",
  "size": "Huge",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 60,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 350,
  "name": "Giant Crab",
  "cr": "1/8",
  "size": "Medium",
  "creatureType": "Beast",
  "ac": 15,
  "hp": 13,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 350,
  "name": "Giant Crocodile",
  "cr": "5",
  "size": "Huge",
  "creatureType": "Beast",
  "ac": 14,
  "hp": 85,
  "primitives": []
 },
 {
  "page": 350,
  "name": "Giant Eagle",
  "cr": "1",
  "size": "Large",
  "creatureType": "Celestial",
  "ac": 13,
  "hp": 26,
  "primitives": []
 },
 {
  "page": 351,
  "name": "Giant Elk",
  "cr": "2",
  "size": "Huge",
  "creatureType": "Celestial",
  "ac": 14,
  "hp": 42,
  "primitives": []
 },
 {
  "page": 351,
  "name": "Giant Fire Beetle",
  "cr": "0",
  "size": "Small",
  "creatureType": "Beast",
  "ac": 13,
  "hp": 4,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 351,
  "name": "Giant Frog",
  "cr": "1/4",
  "size": "Medium",
  "creatureType": "Beast",
  "ac": 11,
  "hp": 18,
  "primitives": []
 },
 {
  "page": 351,
  "name": "Giant Goat",
  "cr": "1/2",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 11,
  "hp": 19,
  "primitives": []
 },
 {
  "page": 352,
  "name": "Giant Hyena",
  "cr": "1",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 45,
  "primitives": []
 },
 {
  "page": 352,
  "name": "Giant Lizard",
  "cr": "1/4",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 19,
  "primitives": []
 },
 {
  "page": 352,
  "name": "Giant Octopus",
  "cr": "1",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 11,
  "hp": 45,
  "primitives": []
 },
 {
  "page": 352,
  "name": "Giant Owl",
  "cr": "1/4",
  "size": "Large",
  "creatureType": "Celestial",
  "ac": 12,
  "hp": 19,
  "primitives": [
   "M01"
  ]
 },
 {
  "page": 353,
  "name": "Giant Rat",
  "cr": "1/8",
  "size": "Small",
  "creatureType": "Beast",
  "ac": 13,
  "hp": 7,
  "primitives": []
 },
 {
  "page": 353,
  "name": "Giant Scorpion",
  "cr": "3",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 15,
  "hp": 52,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 353,
  "name": "Giant Seahorse",
  "cr": "1/2",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 14,
  "hp": 16,
  "primitives": []
 },
 {
  "page": 353,
  "name": "Giant Shark",
  "cr": "5",
  "size": "Huge",
  "creatureType": "Beast",
  "ac": 13,
  "hp": 92,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 353,
  "name": "Giant Spider",
  "cr": "1",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 14,
  "hp": 26,
  "primitives": [
   "M17",
   "M20"
  ]
 },
 {
  "page": 354,
  "name": "Giant Toad",
  "cr": "1",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 11,
  "hp": 39,
  "primitives": []
 },
 {
  "page": 354,
  "name": "Giant Venomous Snake",
  "cr": "1/4",
  "size": "Medium",
  "creatureType": "Beast",
  "ac": 14,
  "hp": 11,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 354,
  "name": "Giant Vulture",
  "cr": "1",
  "size": "Large",
  "creatureType": "Monstrosity",
  "ac": 10,
  "hp": 25,
  "primitives": []
 },
 {
  "page": 354,
  "name": "Giant Wasp",
  "cr": "1/2",
  "size": "Medium",
  "creatureType": "Beast",
  "ac": 13,
  "hp": 22,
  "primitives": []
 },
 {
  "page": 355,
  "name": "Giant Weasel",
  "cr": "1/8",
  "size": "Medium",
  "creatureType": "Beast",
  "ac": 13,
  "hp": 9,
  "primitives": []
 },
 {
  "page": 355,
  "name": "Giant Wolf Spider",
  "cr": "1/4",
  "size": "Medium",
  "creatureType": "Beast",
  "ac": 13,
  "hp": 11,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 288,
  "name": "Gibbering Mouther",
  "cr": "2",
  "size": "Medium",
  "creatureType": "Aberration",
  "ac": 9,
  "hp": 52,
  "primitives": [
   "M11",
   "M13",
   "M14"
  ]
 },
 {
  "page": 289,
  "name": "Glabrezu",
  "cr": "9",
  "size": "Large",
  "creatureType": "Fiend (Demon)",
  "ac": 17,
  "hp": 189,
  "primitives": [
   "M01",
   "M02",
   "M20"
  ]
 },
 {
  "page": 289,
  "name": "Gladiator",
  "cr": "5",
  "size": "Medium or Small",
  "creatureType": "Humanoid",
  "ac": 16,
  "hp": 112,
  "primitives": []
 },
 {
  "page": 289,
  "name": "Gnoll Warrior",
  "cr": "1/2",
  "size": "Medium",
  "creatureType": "Fiend",
  "ac": 15,
  "hp": 27,
  "primitives": []
 },
 {
  "page": 355,
  "name": "Goat",
  "cr": "0",
  "size": "Medium",
  "creatureType": "Beast",
  "ac": 10,
  "hp": 4,
  "primitives": []
 },
 {
  "page": 290,
  "name": "Goblin Boss",
  "cr": "1",
  "size": "Small",
  "creatureType": "Fey (Goblinoid)",
  "ac": 17,
  "hp": 21,
  "primitives": []
 },
 {
  "page": 290,
  "name": "Goblin Minion",
  "cr": "1/8",
  "size": "Small",
  "creatureType": "Fey (Goblinoid)",
  "ac": 12,
  "hp": 7,
  "primitives": []
 },
 {
  "page": 290,
  "name": "Goblin Warrior",
  "cr": "1/4",
  "size": "Small",
  "creatureType": "Fey (Goblinoid)",
  "ac": 15,
  "hp": 10,
  "primitives": []
 },
 {
  "page": 290,
  "name": "Gold Dragon Wyrmling",
  "cr": "3",
  "size": "Medium",
  "creatureType": "Dragon (Metallic)",
  "ac": 17,
  "hp": 60,
  "primitives": [
   "M02",
   "M15",
   "M20"
  ]
 },
 {
  "page": 292,
  "name": "Gorgon",
  "cr": "5",
  "size": "Large",
  "creatureType": "Construct",
  "ac": 19,
  "hp": 114,
  "primitives": [
   "M12"
  ]
 },
 {
  "page": 293,
  "name": "Gray Ooze",
  "cr": "1/2",
  "size": "Medium",
  "creatureType": "Ooze",
  "ac": 9,
  "hp": 22,
  "primitives": [
   "M16",
   "M20"
  ]
 },
 {
  "page": 293,
  "name": "Green Dragon Wyrmling",
  "cr": "2",
  "size": "Medium",
  "creatureType": "Dragon (Chromatic)",
  "ac": 17,
  "hp": 38,
  "primitives": [
   "M02",
   "M20"
  ]
 },
 {
  "page": 295,
  "name": "Green Hag",
  "cr": "3",
  "size": "Medium",
  "creatureType": "Fey",
  "ac": 17,
  "hp": 82,
  "primitives": [
   "M01",
   "M02"
  ]
 },
 {
  "page": 295,
  "name": "Grick",
  "cr": "2",
  "size": "Medium",
  "creatureType": "Aberration",
  "ac": 14,
  "hp": 54,
  "primitives": []
 },
 {
  "page": 295,
  "name": "Griffon",
  "cr": "2",
  "size": "Large",
  "creatureType": "Monstrosity",
  "ac": 12,
  "hp": 59,
  "primitives": []
 },
 {
  "page": 296,
  "name": "Grimlock",
  "cr": "1/4",
  "size": "Medium",
  "creatureType": "Aberration",
  "ac": 11,
  "hp": 11,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 296,
  "name": "Guard",
  "cr": "1/8",
  "size": "Medium or Small",
  "creatureType": "Humanoid",
  "ac": 16,
  "hp": 11,
  "primitives": []
 },
 {
  "page": 296,
  "name": "Guard Captain",
  "cr": "4",
  "size": "Medium or Small",
  "creatureType": "Humanoid",
  "ac": 18,
  "hp": 75,
  "primitives": []
 },
 {
  "page": 296,
  "name": "Guardian Naga",
  "cr": "10",
  "size": "Large",
  "creatureType": "Celestial",
  "ac": 18,
  "hp": 136,
  "primitives": [
   "M01",
   "M02"
  ]
 },
 {
  "page": 297,
  "name": "Half-Dragon",
  "cr": "5",
  "size": "Medium",
  "creatureType": "Dragon",
  "ac": 18,
  "hp": 105,
  "primitives": [
   "M02",
   "M20"
  ]
 },
 {
  "page": 297,
  "name": "Harpy",
  "cr": "1",
  "size": "Medium",
  "creatureType": "Monstrosity",
  "ac": 11,
  "hp": 38,
  "primitives": [
   "M03",
   "M21"
  ]
 },
 {
  "page": 355,
  "name": "Hawk",
  "cr": "0",
  "size": "Tiny",
  "creatureType": "Beast",
  "ac": 13,
  "hp": 1,
  "primitives": []
 },
 {
  "page": 297,
  "name": "Hell Hound",
  "cr": "3",
  "size": "Medium",
  "creatureType": "Fiend",
  "ac": 15,
  "hp": 58,
  "primitives": [
   "M02"
  ]
 },
 {
  "page": 298,
  "name": "Hezrou",
  "cr": "8",
  "size": "Large",
  "creatureType": "Fiend (Demon)",
  "ac": 18,
  "hp": 157,
  "primitives": []
 },
 {
  "page": 298,
  "name": "Hill Giant",
  "cr": "5",
  "size": "Huge",
  "creatureType": "Giant",
  "ac": 13,
  "hp": 105,
  "primitives": []
 },
 {
  "page": 298,
  "name": "Hippogriff",
  "cr": "1",
  "size": "Large",
  "creatureType": "Monstrosity",
  "ac": 11,
  "hp": 26,
  "primitives": []
 },
 {
  "page": 355,
  "name": "Hippopotamus",
  "cr": "4",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 14,
  "hp": 82,
  "primitives": []
 },
 {
  "page": 299,
  "name": "Hobgoblin Captain",
  "cr": "3",
  "size": "Medium",
  "creatureType": "Fey (Goblinoid)",
  "ac": 17,
  "hp": 58,
  "primitives": []
 },
 {
  "page": 298,
  "name": "Hobgoblin Warrior",
  "cr": "1/2",
  "size": "Medium",
  "creatureType": "Fey (Goblinoid)",
  "ac": 18,
  "hp": 11,
  "primitives": []
 },
 {
  "page": 299,
  "name": "Homunculus",
  "cr": "0",
  "size": "Tiny",
  "creatureType": "Construct",
  "ac": 13,
  "hp": 4,
  "primitives": []
 },
 {
  "page": 299,
  "name": "Horned Devil",
  "cr": "11",
  "size": "Large",
  "creatureType": "Fiend (Devil)",
  "ac": 18,
  "hp": 199,
  "primitives": []
 },
 {
  "page": 356,
  "name": "Hunter Shark",
  "cr": "2",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 45,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 300,
  "name": "Hydra",
  "cr": "8",
  "size": "Huge",
  "creatureType": "Monstrosity",
  "ac": 15,
  "hp": 184,
  "primitives": [
   "M05",
   "M06"
  ]
 },
 {
  "page": 356,
  "name": "Hyena",
  "cr": "0",
  "size": "Medium",
  "creatureType": "Beast",
  "ac": 11,
  "hp": 5,
  "primitives": []
 },
 {
  "page": 300,
  "name": "Ice Devil",
  "cr": "14",
  "size": "Large",
  "creatureType": "Fiend (Devil)",
  "ac": 18,
  "hp": 228,
  "primitives": [
   "M01",
   "M02",
   "M13",
   "M20"
  ]
 },
 {
  "page": 307,
  "name": "Ice Mephit",
  "cr": "1/2",
  "size": "Small",
  "creatureType": "Elemental",
  "ac": 11,
  "hp": 21,
  "primitives": [
   "M01"
  ]
 },
 {
  "page": 300,
  "name": "Imp",
  "cr": "1",
  "size": "Tiny",
  "creatureType": "Fiend (Devil)",
  "ac": 13,
  "hp": 21,
  "primitives": [
   "M01"
  ]
 },
 {
  "page": 301,
  "name": "Incubus",
  "cr": "4",
  "size": "Medium",
  "creatureType": "Fiend",
  "ac": 15,
  "hp": 66,
  "primitives": [
   "M01",
   "M02",
   "M27"
  ]
 },
 {
  "page": 301,
  "name": "Invisible Stalker",
  "cr": "6",
  "size": "Large",
  "creatureType": "Elemental",
  "ac": 14,
  "hp": 97,
  "primitives": [
   "M13",
   "M26"
  ]
 },
 {
  "page": 302,
  "name": "Iron Golem",
  "cr": "16",
  "size": "Large",
  "creatureType": "Construct",
  "ac": 20,
  "hp": 252,
  "primitives": [
   "M02",
   "M07"
  ]
 },
 {
  "page": 356,
  "name": "Jackal",
  "cr": "0",
  "size": "Small",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 3,
  "primitives": []
 },
 {
  "page": 356,
  "name": "Killer Whale",
  "cr": "3",
  "size": "Huge",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 90,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 302,
  "name": "Knight",
  "cr": "3",
  "size": "Medium or Small",
  "creatureType": "Humanoid",
  "ac": 18,
  "hp": 52,
  "primitives": []
 },
 {
  "page": 302,
  "name": "Kobold Warrior",
  "cr": "1/8",
  "size": "Small",
  "creatureType": "Dragon",
  "ac": 14,
  "hp": 7,
  "primitives": []
 },
 {
  "page": 303,
  "name": "Kraken",
  "cr": "23",
  "size": "Gargantuan",
  "creatureType": "Monstrosity (Titan)",
  "ac": 18,
  "hp": 481,
  "primitives": [
   "M02",
   "M20"
  ]
 },
 {
  "page": 303,
  "name": "Lamia",
  "cr": "4",
  "size": "Large",
  "creatureType": "Fiend",
  "ac": 13,
  "hp": 97,
  "primitives": [
   "M01",
   "M02"
  ]
 },
 {
  "page": 304,
  "name": "Lemure",
  "cr": "0",
  "size": "Medium",
  "creatureType": "Fiend (Devil)",
  "ac": 9,
  "hp": 9,
  "primitives": []
 },
 {
  "page": 304,
  "name": "Lich",
  "cr": "21",
  "size": "Medium",
  "creatureType": "Undead (Wizard)",
  "ac": 20,
  "hp": 315,
  "primitives": [
   "M01",
   "M02",
   "M20"
  ]
 },
 {
  "page": 356,
  "name": "Lion",
  "cr": "1",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 22,
  "primitives": []
 },
 {
  "page": 357,
  "name": "Lizard",
  "cr": "0",
  "size": "Tiny",
  "creatureType": "Beast",
  "ac": 10,
  "hp": 2,
  "primitives": []
 },
 {
  "page": 305,
  "name": "Mage",
  "cr": "6",
  "size": "Medium or Small",
  "creatureType": "Humanoid (Wizard)",
  "ac": 15,
  "hp": 81,
  "primitives": [
   "M01",
   "M02"
  ]
 },
 {
  "page": 307,
  "name": "Magma Mephit",
  "cr": "1/2",
  "size": "Small",
  "creatureType": "Elemental",
  "ac": 11,
  "hp": 18,
  "primitives": []
 },
 {
  "page": 305,
  "name": "Magmin",
  "cr": "1/2",
  "size": "Small",
  "creatureType": "Elemental",
  "ac": 14,
  "hp": 13,
  "primitives": []
 },
 {
  "page": 357,
  "name": "Mammoth",
  "cr": "6",
  "size": "Huge",
  "creatureType": "Beast",
  "ac": 13,
  "hp": 126,
  "primitives": []
 },
 {
  "page": 306,
  "name": "Manticore",
  "cr": "3",
  "size": "Large",
  "creatureType": "Monstrosity",
  "ac": 14,
  "hp": 68,
  "primitives": []
 },
 {
  "page": 306,
  "name": "Marilith",
  "cr": "16",
  "size": "Large",
  "creatureType": "Fiend (Demon)",
  "ac": 16,
  "hp": 220,
  "primitives": [
   "M02",
   "M05",
   "M20"
  ]
 },
 {
  "page": 357,
  "name": "Mastiff",
  "cr": "1/8",
  "size": "Medium",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 5,
  "primitives": []
 },
 {
  "page": 306,
  "name": "Medusa",
  "cr": "6",
  "size": "Medium",
  "creatureType": "Monstrosity",
  "ac": 15,
  "hp": 127,
  "primitives": [
   "M02",
   "M12"
  ]
 },
 {
  "page": 308,
  "name": "Merfolk Skirmisher",
  "cr": "1/8",
  "size": "Medium",
  "creatureType": "Elemental",
  "ac": 11,
  "hp": 11,
  "primitives": []
 },
 {
  "page": 308,
  "name": "Merrow",
  "cr": "2",
  "size": "Large",
  "creatureType": "Monstrosity",
  "ac": 13,
  "hp": 45,
  "primitives": []
 },
 {
  "page": 308,
  "name": "Mimic",
  "cr": "2",
  "size": "Medium",
  "creatureType": "Monstrosity",
  "ac": 12,
  "hp": 58,
  "primitives": []
 },
 {
  "page": 309,
  "name": "Minotaur of Baphomet",
  "cr": "3",
  "size": "Large",
  "creatureType": "Monstrosity",
  "ac": 14,
  "hp": 85,
  "primitives": []
 },
 {
  "page": 326,
  "name": "Minotaur Skeleton",
  "cr": "2",
  "size": "Large",
  "creatureType": "Undead",
  "ac": 12,
  "hp": 45,
  "primitives": []
 },
 {
  "page": 357,
  "name": "Mule",
  "cr": "1/8",
  "size": "Medium",
  "creatureType": "Beast",
  "ac": 10,
  "hp": 11,
  "primitives": []
 },
 {
  "page": 309,
  "name": "Mummy",
  "cr": "3",
  "size": "Medium or Small",
  "creatureType": "Undead",
  "ac": 11,
  "hp": 58,
  "primitives": [
   "M09",
   "M11",
   "M21"
  ]
 },
 {
  "page": 309,
  "name": "Mummy Lord",
  "cr": "15",
  "size": "Medium or Small",
  "creatureType": "Undead (Cleric)",
  "ac": 17,
  "hp": 187,
  "primitives": [
   "M01",
   "M02",
   "M09",
   "M11",
   "M17",
   "M20",
   "M27"
  ]
 },
 {
  "page": 310,
  "name": "Nalfeshnee",
  "cr": "13",
  "size": "Large",
  "creatureType": "Fiend (Demon)",
  "ac": 18,
  "hp": 184,
  "primitives": [
   "M02",
   "M20",
   "M21"
  ]
 },
 {
  "page": 311,
  "name": "Night Hag",
  "cr": "5",
  "size": "Medium",
  "creatureType": "Fiend",
  "ac": 17,
  "hp": 112,
  "primitives": [
   "M01",
   "M02",
   "M09",
   "M17",
   "M19",
   "M27"
  ]
 },
 {
  "page": 311,
  "name": "Nightmare",
  "cr": "3",
  "size": "Large",
  "creatureType": "Fiend",
  "ac": 13,
  "hp": 68,
  "primitives": [
   "M19"
  ]
 },
 {
  "page": 312,
  "name": "Noble",
  "cr": "1/8",
  "size": "Medium or Small",
  "creatureType": "Humanoid",
  "ac": 15,
  "hp": 9,
  "primitives": []
 },
 {
  "page": 312,
  "name": "Ochre Jelly",
  "cr": "2",
  "size": "Large",
  "creatureType": "Ooze",
  "ac": 8,
  "hp": 52,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 357,
  "name": "Octopus",
  "cr": "0",
  "size": "Small",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 3,
  "primitives": []
 },
 {
  "page": 312,
  "name": "Ogre",
  "cr": "2",
  "size": "Large",
  "creatureType": "Giant",
  "ac": 11,
  "hp": 68,
  "primitives": []
 },
 {
  "page": 344,
  "name": "Ogre Zombie",
  "cr": "2",
  "size": "Large",
  "creatureType": "Undead",
  "ac": 8,
  "hp": 85,
  "primitives": []
 },
 {
  "page": 312,
  "name": "Oni",
  "cr": "7",
  "size": "Large",
  "creatureType": "Fiend",
  "ac": 17,
  "hp": 119,
  "primitives": [
   "M01",
   "M02"
  ]
 },
 {
  "page": 313,
  "name": "Otyugh",
  "cr": "5",
  "size": "Large",
  "creatureType": "Aberration",
  "ac": 14,
  "hp": 104,
  "primitives": [
   "M09"
  ]
 },
 {
  "page": 358,
  "name": "Owl",
  "cr": "0",
  "size": "Tiny",
  "creatureType": "Beast",
  "ac": 11,
  "hp": 1,
  "primitives": []
 },
 {
  "page": 313,
  "name": "Owlbear",
  "cr": "3",
  "size": "Large",
  "creatureType": "Monstrosity",
  "ac": 13,
  "hp": 59,
  "primitives": []
 },
 {
  "page": 358,
  "name": "Panther",
  "cr": "1/4",
  "size": "Medium",
  "creatureType": "Beast",
  "ac": 13,
  "hp": 13,
  "primitives": []
 },
 {
  "page": 313,
  "name": "Pegasus",
  "cr": "2",
  "size": "Large",
  "creatureType": "Celestial",
  "ac": 12,
  "hp": 59,
  "primitives": []
 },
 {
  "page": 313,
  "name": "Phase Spider",
  "cr": "3",
  "size": "Large",
  "creatureType": "Monstrosity",
  "ac": 14,
  "hp": 45,
  "primitives": [
   "M11",
   "M19",
   "M20"
  ]
 },
 {
  "page": 358,
  "name": "Piranha",
  "cr": "0",
  "size": "Tiny",
  "creatureType": "Beast",
  "ac": 13,
  "hp": 1,
  "primitives": []
 },
 {
  "page": 314,
  "name": "Pirate",
  "cr": "1",
  "size": "Medium or Small",
  "creatureType": "Humanoid",
  "ac": 14,
  "hp": 33,
  "primitives": []
 },
 {
  "page": 314,
  "name": "Pirate Captain",
  "cr": "6",
  "size": "Medium or Small",
  "creatureType": "Humanoid",
  "ac": 17,
  "hp": 84,
  "primitives": []
 },
 {
  "page": 314,
  "name": "Pit Fiend",
  "cr": "20",
  "size": "Large",
  "creatureType": "Fiend (Devil)",
  "ac": 21,
  "hp": 337,
  "primitives": [
   "M01",
   "M02",
   "M20",
   "M21"
  ]
 },
 {
  "page": 315,
  "name": "Planetar",
  "cr": "16",
  "size": "Large",
  "creatureType": "Celestial (Angel)",
  "ac": 19,
  "hp": 262,
  "primitives": [
   "M01",
   "M02",
   "M20"
  ]
 },
 {
  "page": 358,
  "name": "Plesiosaurus",
  "cr": "2",
  "size": "Large",
  "creatureType": "Beast (Dinosaur)",
  "ac": 13,
  "hp": 68,
  "primitives": []
 },
 {
  "page": 359,
  "name": "Polar Bear",
  "cr": "2",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 42,
  "primitives": []
 },
 {
  "page": 359,
  "name": "Pony",
  "cr": "1/8",
  "size": "Medium",
  "creatureType": "Beast",
  "ac": 10,
  "hp": 11,
  "primitives": []
 },
 {
  "page": 316,
  "name": "Priest",
  "cr": "2",
  "size": "Medium or Small",
  "creatureType": "Humanoid (Cleric)",
  "ac": 13,
  "hp": 38,
  "primitives": [
   "M01",
   "M02"
  ]
 },
 {
  "page": 316,
  "name": "Priest Acolyte",
  "cr": "1/4",
  "size": "Medium or Small",
  "creatureType": "Humanoid (Cleric)",
  "ac": 13,
  "hp": 11,
  "primitives": [
   "M01"
  ]
 },
 {
  "page": 316,
  "name": "Pseudodragon",
  "cr": "1/4",
  "size": "Tiny",
  "creatureType": "Dragon",
  "ac": 14,
  "hp": 10,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 359,
  "name": "Pteranodon",
  "cr": "1/4",
  "size": "Medium",
  "creatureType": "Beast (Dinosaur)",
  "ac": 13,
  "hp": 13,
  "primitives": []
 },
 {
  "page": 316,
  "name": "Purple Worm",
  "cr": "15",
  "size": "Gargantuan",
  "creatureType": "Monstrosity",
  "ac": 18,
  "hp": 247,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 317,
  "name": "Quasit",
  "cr": "1",
  "size": "Tiny",
  "creatureType": "Fiend (Demon)",
  "ac": 13,
  "hp": 25,
  "primitives": [
   "M01"
  ]
 },
 {
  "page": 317,
  "name": "Rakshasa",
  "cr": "13",
  "size": "Medium",
  "creatureType": "Fiend",
  "ac": 17,
  "hp": 221,
  "primitives": [
   "M01",
   "M02",
   "M08",
   "M20",
   "M27"
  ]
 },
 {
  "page": 359,
  "name": "Rat",
  "cr": "0",
  "size": "Tiny",
  "creatureType": "Beast",
  "ac": 10,
  "hp": 1,
  "primitives": []
 },
 {
  "page": 359,
  "name": "Raven",
  "cr": "0",
  "size": "Tiny",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 2,
  "primitives": []
 },
 {
  "page": 318,
  "name": "Red Dragon Wyrmling",
  "cr": "4",
  "size": "Medium",
  "creatureType": "Dragon (Chromatic)",
  "ac": 17,
  "hp": 75,
  "primitives": [
   "M02",
   "M20"
  ]
 },
 {
  "page": 360,
  "name": "Reef Shark",
  "cr": "1/2",
  "size": "Medium",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 22,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 319,
  "name": "Remorhaz",
  "cr": "11",
  "size": "Huge",
  "creatureType": "Monstrosity",
  "ac": 17,
  "hp": 195,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 360,
  "name": "Rhinoceros",
  "cr": "2",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 13,
  "hp": 45,
  "primitives": []
 },
 {
  "page": 360,
  "name": "Riding Horse",
  "cr": "1/4",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 11,
  "hp": 13,
  "primitives": []
 },
 {
  "page": 320,
  "name": "Roc",
  "cr": "11",
  "size": "Gargantuan",
  "creatureType": "Monstrosity",
  "ac": 15,
  "hp": 248,
  "primitives": [
   "M02"
  ]
 },
 {
  "page": 320,
  "name": "Roper",
  "cr": "5",
  "size": "Large",
  "creatureType": "Aberration",
  "ac": 20,
  "hp": 93,
  "primitives": [
   "M17"
  ]
 },
 {
  "page": 320,
  "name": "Rust Monster",
  "cr": "1/2",
  "size": "Medium",
  "creatureType": "Monstrosity",
  "ac": 14,
  "hp": 33,
  "primitives": [
   "M16"
  ]
 },
 {
  "page": 360,
  "name": "Saber-Toothed Tiger",
  "cr": "2",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 13,
  "hp": 52,
  "primitives": []
 },
 {
  "page": 321,
  "name": "Sahuagin Warrior",
  "cr": "1/2",
  "size": "Medium",
  "creatureType": "Fiend",
  "ac": 12,
  "hp": 22,
  "primitives": [
   "M26"
  ]
 },
 {
  "page": 321,
  "name": "Salamander",
  "cr": "5",
  "size": "Large",
  "creatureType": "Elemental",
  "ac": 15,
  "hp": 90,
  "primitives": []
 },
 {
  "page": 321,
  "name": "Satyr",
  "cr": "1/2",
  "size": "Medium",
  "creatureType": "Fey",
  "ac": 13,
  "hp": 31,
  "primitives": []
 },
 {
  "page": 360,
  "name": "Scorpion",
  "cr": "0",
  "size": "Tiny",
  "creatureType": "Beast",
  "ac": 11,
  "hp": 1,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 322,
  "name": "Scout",
  "cr": "1/2",
  "size": "Medium or Small",
  "creatureType": "Humanoid",
  "ac": 13,
  "hp": 16,
  "primitives": []
 },
 {
  "page": 322,
  "name": "Sea Hag",
  "cr": "2",
  "size": "Medium",
  "creatureType": "Fey",
  "ac": 14,
  "hp": 52,
  "primitives": [
   "M01",
   "M11",
   "M21"
  ]
 },
 {
  "page": 361,
  "name": "Seahorse",
  "cr": "0",
  "size": "Tiny",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 1,
  "primitives": []
 },
 {
  "page": 322,
  "name": "Shadow",
  "cr": "1/2",
  "size": "Medium",
  "creatureType": "Undead",
  "ac": 12,
  "hp": 27,
  "primitives": [
   "M10",
   "M11"
  ]
 },
 {
  "page": 323,
  "name": "Shambling Mound",
  "cr": "5",
  "size": "Large",
  "creatureType": "Plant",
  "ac": 15,
  "hp": 110,
  "primitives": [
   "M07",
   "M20"
  ]
 },
 {
  "page": 323,
  "name": "Shield Guardian",
  "cr": "7",
  "size": "Large",
  "creatureType": "Construct",
  "ac": 17,
  "hp": 142,
  "primitives": [
   "M01",
   "M02",
   "M20",
   "M25"
  ]
 },
 {
  "page": 286,
  "name": "Shrieker Fungus",
  "cr": "0",
  "size": "Medium",
  "creatureType": "Plant",
  "ac": 5,
  "hp": 13,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 324,
  "name": "Silver Dragon Wyrmling",
  "cr": "2",
  "size": "Medium",
  "creatureType": "Dragon (Metallic)",
  "ac": 17,
  "hp": 45,
  "primitives": [
   "M02",
   "M12",
   "M20"
  ]
 },
 {
  "page": 325,
  "name": "Skeleton",
  "cr": "1/4",
  "size": "Medium",
  "creatureType": "Undead",
  "ac": 14,
  "hp": 13,
  "primitives": []
 },
 {
  "page": 326,
  "name": "Solar",
  "cr": "21",
  "size": "Large",
  "creatureType": "Celestial (Angel)",
  "ac": 21,
  "hp": 297,
  "primitives": [
   "M01",
   "M02",
   "M11",
   "M20"
  ]
 },
 {
  "page": 327,
  "name": "Specter",
  "cr": "1",
  "size": "Medium",
  "creatureType": "Undead",
  "ac": 12,
  "hp": 22,
  "primitives": [
   "M09"
  ]
 },
 {
  "page": 327,
  "name": "Sphinx of Lore",
  "cr": "11",
  "size": "Large",
  "creatureType": "Celestial",
  "ac": 17,
  "hp": 170,
  "primitives": [
   "M01",
   "M02",
   "M20"
  ]
 },
 {
  "page": 328,
  "name": "Sphinx of Valor",
  "cr": "17",
  "size": "Large",
  "creatureType": "Celestial",
  "ac": 17,
  "hp": 199,
  "primitives": [
   "M01",
   "M02",
   "M20"
  ]
 },
 {
  "page": 327,
  "name": "Sphinx of Wonder",
  "cr": "1",
  "size": "Tiny",
  "creatureType": "Celestial",
  "ac": 13,
  "hp": 24,
  "primitives": []
 },
 {
  "page": 361,
  "name": "Spider",
  "cr": "0",
  "size": "Tiny",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 1,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 329,
  "name": "Spirit Naga",
  "cr": "8",
  "size": "Large",
  "creatureType": "Fiend",
  "ac": 17,
  "hp": 135,
  "primitives": [
   "M01",
   "M02"
  ]
 },
 {
  "page": 329,
  "name": "Sprite",
  "cr": "1/4",
  "size": "Tiny",
  "creatureType": "Fey",
  "ac": 15,
  "hp": 10,
  "primitives": [
   "M01"
  ]
 },
 {
  "page": 329,
  "name": "Spy",
  "cr": "1",
  "size": "Medium or Small",
  "creatureType": "Humanoid",
  "ac": 12,
  "hp": 27,
  "primitives": []
 },
 {
  "page": 308,
  "name": "Steam Mephit",
  "cr": "1/4",
  "size": "Small",
  "creatureType": "Elemental",
  "ac": 10,
  "hp": 17,
  "primitives": []
 },
 {
  "page": 329,
  "name": "Stirge",
  "cr": "1/8",
  "size": "Tiny",
  "creatureType": "Monstrosity",
  "ac": 13,
  "hp": 5,
  "primitives": []
 },
 {
  "page": 330,
  "name": "Stone Giant",
  "cr": "7",
  "size": "Huge",
  "creatureType": "Giant",
  "ac": 17,
  "hp": 126,
  "primitives": [
   "M02"
  ]
 },
 {
  "page": 330,
  "name": "Stone Golem",
  "cr": "10",
  "size": "Large",
  "creatureType": "Construct",
  "ac": 18,
  "hp": 220,
  "primitives": [
   "M01",
   "M02"
  ]
 },
 {
  "page": 330,
  "name": "Storm Giant",
  "cr": "13",
  "size": "Huge",
  "creatureType": "Giant",
  "ac": 16,
  "hp": 230,
  "primitives": [
   "M01",
   "M02",
   "M20"
  ]
 },
 {
  "page": 331,
  "name": "Succubus",
  "cr": "4",
  "size": "Medium",
  "creatureType": "Fiend",
  "ac": 15,
  "hp": 71,
  "primitives": [
   "M01",
   "M02",
   "M09"
  ]
 },
 {
  "page": 361,
  "name": "Swarm of Bats",
  "cr": "1/4",
  "size": "Large",
  "creatureType": "Swarm of Tiny Beasts",
  "ac": 12,
  "hp": 11,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 278,
  "name": "Swarm of Crawling Claws",
  "cr": "3",
  "size": "Medium",
  "creatureType": "Swarm of Tiny Undead",
  "ac": 12,
  "hp": 49,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 361,
  "name": "Swarm of Insects",
  "cr": "1/2",
  "size": "Medium",
  "creatureType": "Swarm of Tiny Beasts",
  "ac": 11,
  "hp": 19,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 362,
  "name": "Swarm of Piranhas",
  "cr": "1",
  "size": "Medium",
  "creatureType": "Swarm of Tiny Beasts",
  "ac": 13,
  "hp": 28,
  "primitives": []
 },
 {
  "page": 362,
  "name": "Swarm of Rats",
  "cr": "1/4",
  "size": "Medium",
  "creatureType": "Swarm of Tiny Beasts",
  "ac": 10,
  "hp": 14,
  "primitives": []
 },
 {
  "page": 362,
  "name": "Swarm of Ravens",
  "cr": "1/4",
  "size": "Medium",
  "creatureType": "Swarm of Tiny Beasts",
  "ac": 12,
  "hp": 11,
  "primitives": []
 },
 {
  "page": 362,
  "name": "Swarm of Venomous Snakes",
  "cr": "2",
  "size": "Medium",
  "creatureType": "Swarm of Tiny Beasts",
  "ac": 14,
  "hp": 36,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 331,
  "name": "Tarrasque",
  "cr": "30",
  "size": "Gargantuan",
  "creatureType": "Monstrosity (Titan)",
  "ac": 25,
  "hp": 697,
  "primitives": [
   "M02",
   "M03",
   "M08",
   "M13",
   "M20",
   "M28"
  ]
 },
 {
  "page": 363,
  "name": "Tiger",
  "cr": "1",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 13,
  "hp": 30,
  "primitives": []
 },
 {
  "page": 332,
  "name": "Tough",
  "cr": "1/2",
  "size": "Medium or Small",
  "creatureType": "Humanoid",
  "ac": 12,
  "hp": 32,
  "primitives": []
 },
 {
  "page": 332,
  "name": "Tough Boss",
  "cr": "4",
  "size": "Medium or Small",
  "creatureType": "Humanoid",
  "ac": 16,
  "hp": 82,
  "primitives": []
 },
 {
  "page": 333,
  "name": "Treant",
  "cr": "9",
  "size": "Huge",
  "creatureType": "Plant",
  "ac": 16,
  "hp": 138,
  "primitives": [
   "M02"
  ]
 },
 {
  "page": 363,
  "name": "Triceratops",
  "cr": "5",
  "size": "Huge",
  "creatureType": "Beast (Dinosaur)",
  "ac": 14,
  "hp": 114,
  "primitives": []
 },
 {
  "page": 333,
  "name": "Troll",
  "cr": "5",
  "size": "Large",
  "creatureType": "Giant",
  "ac": 15,
  "hp": 94,
  "primitives": [
   "M02"
  ]
 },
 {
  "page": 333,
  "name": "Troll Limb",
  "cr": "1/2",
  "size": "Small",
  "creatureType": "Giant",
  "ac": 13,
  "hp": 14,
  "primitives": []
 },
 {
  "page": 363,
  "name": "Tyrannosaurus Rex",
  "cr": "8",
  "size": "Huge",
  "creatureType": "Beast (Dinosaur)",
  "ac": 13,
  "hp": 136,
  "primitives": []
 },
 {
  "page": 334,
  "name": "Unicorn",
  "cr": "5",
  "size": "Large",
  "creatureType": "Celestial",
  "ac": 12,
  "hp": 97,
  "primitives": [
   "M01",
   "M02"
  ]
 },
 {
  "page": 335,
  "name": "Vampire",
  "cr": "13",
  "size": "Medium or Small",
  "creatureType": "Undead",
  "ac": 16,
  "hp": 195,
  "primitives": [
   "M01",
   "M09"
  ]
 },
 {
  "page": 334,
  "name": "Vampire Familiar",
  "cr": "3",
  "size": "Medium or Small",
  "creatureType": "Humanoid",
  "ac": 15,
  "hp": 65,
  "primitives": [
   "M11"
  ]
 },
 {
  "page": 334,
  "name": "Vampire Spawn",
  "cr": "5",
  "size": "Medium or Small",
  "creatureType": "Undead",
  "ac": 16,
  "hp": 90,
  "primitives": [
   "M09"
  ]
 },
 {
  "page": 363,
  "name": "Venomous Snake",
  "cr": "1/8",
  "size": "Tiny",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 5,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 286,
  "name": "Violet Fungus",
  "cr": "1/4",
  "size": "Medium",
  "creatureType": "Plant",
  "ac": 5,
  "hp": 18,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 336,
  "name": "Vrock",
  "cr": "6",
  "size": "Large",
  "creatureType": "Fiend (Demon)",
  "ac": 15,
  "hp": 152,
  "primitives": [
   "M02"
  ]
 },
 {
  "page": 363,
  "name": "Vulture",
  "cr": "0",
  "size": "Medium",
  "creatureType": "Beast",
  "ac": 10,
  "hp": 5,
  "primitives": []
 },
 {
  "page": 364,
  "name": "Warhorse",
  "cr": "1/2",
  "size": "Large",
  "creatureType": "Beast",
  "ac": 11,
  "hp": 19,
  "primitives": []
 },
 {
  "page": 326,
  "name": "Warhorse Skeleton",
  "cr": "1/2",
  "size": "Large",
  "creatureType": "Undead",
  "ac": 13,
  "hp": 22,
  "primitives": []
 },
 {
  "page": 336,
  "name": "Warrior Infantry",
  "cr": "1/8",
  "size": "Medium or Small",
  "creatureType": "Humanoid",
  "ac": 13,
  "hp": 9,
  "primitives": []
 },
 {
  "page": 337,
  "name": "Warrior Veteran",
  "cr": "3",
  "size": "Medium or Small",
  "creatureType": "Humanoid",
  "ac": 17,
  "hp": 65,
  "primitives": []
 },
 {
  "page": 337,
  "name": "Water Elemental",
  "cr": "5",
  "size": "Large",
  "creatureType": "Elemental",
  "ac": 14,
  "hp": 114,
  "primitives": [
   "M02",
   "M26"
  ]
 },
 {
  "page": 364,
  "name": "Weasel",
  "cr": "0",
  "size": "Tiny",
  "creatureType": "Beast",
  "ac": 13,
  "hp": 1,
  "primitives": []
 },
 {
  "page": 337,
  "name": "Werebear",
  "cr": "5",
  "size": "Medium or Small",
  "creatureType": "Monstrosity (Lycanthrope)",
  "ac": 15,
  "hp": 135,
  "primitives": [
   "M11",
   "M12",
   "M21"
  ]
 },
 {
  "page": 338,
  "name": "Wereboar",
  "cr": "4",
  "size": "Medium or Small",
  "creatureType": "Monstrosity (Lycanthrope)",
  "ac": 15,
  "hp": 97,
  "primitives": [
   "M11",
   "M12",
   "M21"
  ]
 },
 {
  "page": 338,
  "name": "Wererat",
  "cr": "2",
  "size": "Medium or Small",
  "creatureType": "Monstrosity (Lycanthrope)",
  "ac": 13,
  "hp": 60,
  "primitives": [
   "M11",
   "M12",
   "M21"
  ]
 },
 {
  "page": 339,
  "name": "Weretiger",
  "cr": "4",
  "size": "Medium or Small",
  "creatureType": "Monstrosity (Lycanthrope)",
  "ac": 12,
  "hp": 120,
  "primitives": [
   "M11",
   "M12",
   "M21"
  ]
 },
 {
  "page": 339,
  "name": "Werewolf",
  "cr": "3",
  "size": "Medium or Small",
  "creatureType": "Monstrosity (Lycanthrope)",
  "ac": 15,
  "hp": 71,
  "primitives": [
   "M11",
   "M12",
   "M21"
  ]
 },
 {
  "page": 339,
  "name": "White Dragon Wyrmling",
  "cr": "2",
  "size": "Medium",
  "creatureType": "Dragon (Chromatic)",
  "ac": 16,
  "hp": 32,
  "primitives": [
   "M02",
   "M20"
  ]
 },
 {
  "page": 341,
  "name": "Wight",
  "cr": "3",
  "size": "Medium",
  "creatureType": "Undead",
  "ac": 14,
  "hp": 82,
  "primitives": [
   "M09"
  ]
 },
 {
  "page": 341,
  "name": "Will-o’-Wisp",
  "cr": "2",
  "size": "Tiny",
  "creatureType": "Undead",
  "ac": 19,
  "hp": 27,
  "primitives": [
   "M03",
   "M11"
  ]
 },
 {
  "page": 342,
  "name": "Winter Wolf",
  "cr": "3",
  "size": "Large",
  "creatureType": "Monstrosity",
  "ac": 13,
  "hp": 75,
  "primitives": []
 },
 {
  "page": 364,
  "name": "Wolf",
  "cr": "1/4",
  "size": "Medium",
  "creatureType": "Beast",
  "ac": 12,
  "hp": 11,
  "primitives": []
 },
 {
  "page": 342,
  "name": "Worg",
  "cr": "1/2",
  "size": "Large",
  "creatureType": "Fey",
  "ac": 13,
  "hp": 26,
  "primitives": []
 },
 {
  "page": 342,
  "name": "Wraith",
  "cr": "5",
  "size": "Medium or Small",
  "creatureType": "Undead",
  "ac": 13,
  "hp": 67,
  "primitives": [
   "M09"
  ]
 },
 {
  "page": 343,
  "name": "Wyvern",
  "cr": "6",
  "size": "Large",
  "creatureType": "Dragon",
  "ac": 14,
  "hp": 127,
  "primitives": []
 },
 {
  "page": 343,
  "name": "Xorn",
  "cr": "5",
  "size": "Medium",
  "creatureType": "Elemental",
  "ac": 19,
  "hp": 84,
  "primitives": [
   "M20"
  ]
 },
 {
  "page": 264,
  "name": "Young Black Dragon",
  "cr": "7",
  "size": "Large",
  "creatureType": "Dragon (Chromatic)",
  "ac": 18,
  "hp": 127,
  "primitives": [
   "M02",
   "M20"
  ]
 },
 {
  "page": 266,
  "name": "Young Blue Dragon",
  "cr": "9",
  "size": "Large",
  "creatureType": "Dragon (Chromatic)",
  "ac": 18,
  "hp": 152,
  "primitives": [
   "M02",
   "M20"
  ]
 },
 {
  "page": 268,
  "name": "Young Brass Dragon",
  "cr": "6",
  "size": "Large",
  "creatureType": "Dragon (Metallic)",
  "ac": 17,
  "hp": 110,
  "primitives": [
   "M02",
   "M12",
   "M20"
  ]
 },
 {
  "page": 270,
  "name": "Young Bronze Dragon",
  "cr": "8",
  "size": "Large",
  "creatureType": "Dragon (Metallic)",
  "ac": 17,
  "hp": 142,
  "primitives": [
   "M02",
   "M20"
  ]
 },
 {
  "page": 276,
  "name": "Young Copper Dragon",
  "cr": "7",
  "size": "Large",
  "creatureType": "Dragon (Metallic)",
  "ac": 17,
  "hp": 119,
  "primitives": [
   "M02",
   "M13",
   "M20"
  ]
 },
 {
  "page": 291,
  "name": "Young Gold Dragon",
  "cr": "10",
  "size": "Large",
  "creatureType": "Dragon (Metallic)",
  "ac": 18,
  "hp": 178,
  "primitives": [
   "M02",
   "M15",
   "M20"
  ]
 },
 {
  "page": 293,
  "name": "Young Green Dragon",
  "cr": "8",
  "size": "Large",
  "creatureType": "Dragon (Chromatic)",
  "ac": 18,
  "hp": 136,
  "primitives": [
   "M02",
   "M20"
  ]
 },
 {
  "page": 318,
  "name": "Young Red Dragon",
  "cr": "10",
  "size": "Large",
  "creatureType": "Dragon (Chromatic)",
  "ac": 18,
  "hp": 178,
  "primitives": [
   "M02",
   "M20"
  ]
 },
 {
  "page": 324,
  "name": "Young Silver Dragon",
  "cr": "9",
  "size": "Large",
  "creatureType": "Dragon (Metallic)",
  "ac": 18,
  "hp": 168,
  "primitives": [
   "M02",
   "M12",
   "M20"
  ]
 },
 {
  "page": 340,
  "name": "Young White Dragon",
  "cr": "6",
  "size": "Large",
  "creatureType": "Dragon (Chromatic)",
  "ac": 17,
  "hp": 123,
  "primitives": [
   "M02",
   "M20"
  ]
 },
 {
  "page": 343,
  "name": "Zombie",
  "cr": "1/4",
  "size": "Medium",
  "creatureType": "Undead",
  "ac": 8,
  "hp": 15,
  "primitives": []
 }
];

export const SRD_AUDIT_CR_ROWS: SrdAuditCrRow[] = [
 {
  "cr": 26,
  "proficiencyBonus": 8,
  "expectedAc": 19,
  "hpLow": 626,
  "hpHigh": 670,
  "expectedAttackBonus": 12,
  "dprLow": 231,
  "dprHigh": 248,
  "expectedSaveDc": 21
 },
 {
  "cr": 27,
  "proficiencyBonus": 8,
  "expectedAc": 19,
  "hpLow": 671,
  "hpHigh": 715,
  "expectedAttackBonus": 13,
  "dprLow": 249,
  "dprHigh": 266,
  "expectedSaveDc": 22
 },
 {
  "cr": 28,
  "proficiencyBonus": 8,
  "expectedAc": 19,
  "hpLow": 716,
  "hpHigh": 760,
  "expectedAttackBonus": 13,
  "dprLow": 267,
  "dprHigh": 284,
  "expectedSaveDc": 22
 },
 {
  "cr": 29,
  "proficiencyBonus": 9,
  "expectedAc": 19,
  "hpLow": 761,
  "hpHigh": 805,
  "expectedAttackBonus": 13,
  "dprLow": 285,
  "dprHigh": 302,
  "expectedSaveDc": 22
 },
 {
  "cr": 30,
  "proficiencyBonus": 9,
  "expectedAc": 19,
  "hpLow": 806,
  "hpHigh": 850,
  "expectedAttackBonus": 14,
  "dprLow": 303,
  "dprHigh": 320,
  "expectedSaveDc": 23
 }
];

export const SRD_AUDIT_BY_NAME = new Map(SRD_AUDIT_CHASSIS.map(c => [c.name, c]));
